<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="OfficeAppManifest" elementFormDefault="qualified" version="1.0"
    targetNamespace="http://schemas.microsoft.com/office/appforoffice/1.0"
    xmlns="http://schemas.microsoft.com/office/appforoffice/1.0"
    xmlns:ver="http://schemas.microsoft.com/office/appforoffice/1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="NonEmptyString">
    <xs:annotation>
      <xs:documentation>
        定义一个不能为空并且可以未绑定的字符串。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ShortString">
    <xs:annotation>
      <xs:documentation>
        定义一个必须包含 1 到 125 个字符的字符串。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="125"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="LongString">
    <xs:annotation>
      <xs:documentation>
        定义一个必须包含 1 到 250 个字符的字符串。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="250"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="URL">
    <xs:annotation>
      <xs:documentation>
        定义一个容纳统一资源定位器并且必须包含 1 到 2048 个字符的字符串。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:anyURI">
      <xs:minLength value="1"/>
      <xs:maxLength value="2048"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="LocaleOverride">
    <xs:annotation>
      <xs:documentation>
        为未绑定的字符串定义多个区域设置支持。
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="Locale" type="CultureName" use="required">
      <xs:annotation>
        <xs:documentation>为此替代指定区域设置的区域性名称。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Value" type="NonEmptyString" use="required">
      <xs:annotation>
        <xs:documentation>指定设置的值，为指定的区域设置表示。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="ShortLocaleOverride">
    <xs:annotation>
      <xs:documentation>
        为短字符串定义多个区域设置支持。
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="Locale" type="CultureName" use="required">
      <xs:annotation>
        <xs:documentation>为此替代指定区域设置的区域性名称。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Value" type="ShortString" use="required">
      <xs:annotation>
        <xs:documentation>指定设置的值，为指定的区域设置表示。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="LongLocaleOverride">
    <xs:annotation>
      <xs:documentation>
        为长字符串定义多个区域设置支持。
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="Locale" type="CultureName" use="required">
      <xs:annotation>
        <xs:documentation>为此替代指定区域设置的区域性名称。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Value" type="LongString" use="required">
      <xs:annotation>
        <xs:documentation>指定设置的值，为指定的区域设置表示。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="URLLocaleOverride">
    <xs:annotation>
      <xs:documentation>
        为 URL 字符串定义多个区域设置支持。
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="Locale" type="CultureName" use="required">
      <xs:annotation>
        <xs:documentation>为此替代指定区域设置的区域性名称。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Value" type="URL" use="required">
      <xs:annotation>
        <xs:documentation>指定设置的值，为指定的区域设置表示。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="LocaleAwareSetting">
    <xs:annotation>
      <xs:documentation>
        定义一个设置，该设置未绑定，可感知区域设置，并且可以为不同于默认区域设置的其他区域设置指定。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Override" type="LocaleOverride" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>提供一种方式来为其他区域设置指定此设置的值。</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="DefaultValue" type="NonEmptyString" use="required">
      <xs:annotation>
        <xs:documentation>
          指定此设置的默认值，为 <b>DefaultLocale</b> 元素中指定的区域设置表示。
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="ShortLocaleAwareSetting">
    <xs:annotation>
      <xs:documentation>
        定义一个设置，该设置是短字符串，可感知区域设置，并且可以为不同于默认区域设置的其他区域设置指定。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Override" type="ShortLocaleOverride" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>提供一种方式来为其他区域设置指定此设置的值。</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="DefaultValue" type="ShortString" use="required">
      <xs:annotation>
        <xs:documentation>
          指定此设置的默认值，为 <b>DefaultLocale</b> 元素中指定的区域设置表示。
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="LongLocaleAwareSetting">
    <xs:annotation>
      <xs:documentation>
        定义一个设置，该设置是长字符串，可感知区域设置，并且可以为不同于默认区域设置的其他区域设置指定。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Override" type="LongLocaleOverride" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>提供一种方式来为其他区域设置指定此设置的值。</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="DefaultValue" type="LongString" use="required">
      <xs:annotation>
        <xs:documentation>
          指定此设置的默认值，为 <b>DefaultLocale</b> 元素中指定的区域设置表示。
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="URLLocaleAwareSetting">
    <xs:annotation>
      <xs:documentation>
        定义一个 URL 设置，该设置可感知区域设置，并且可以为不同于默认区域设置的其他区域设置指定。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Override" type="URLLocaleOverride" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>提供一种方式来为其他区域设置指定此设置的值。</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="DefaultValue" type="URL" use="required">
      <xs:annotation>
        <xs:documentation>
          指定此设置的默认值，为 <b>DefaultLocale</b> 元素中指定的区域设置表示。
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="UUID">
    <xs:annotation>
      <xs:documentation>URN UUID 或 GUID 的支持的表示形式。</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="(urn:uuid:)?[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="AlternateId">
    <xs:annotation>
      <xs:documentation>按照 Office 应用商店的定义来定义备用 ID 类型。</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value=".{5,12}\\WA[0-9]{9}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CultureName">
    <xs:annotation>
      <xs:documentation>表示限定的字符串中使用的语言的区域性名称。</xs:documentation>
    </xs:annotation>
    <!-- The culture names follow the BCP 47 standard. -->
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]{2,3}-[a-zA-Z0-9]{3,8}(-[a-zA-Z]{2,3})?|[a-zA-Z]{2,3}(-[a-zA-Z]{2,3}(_tradnl|\.pseudo|-[a-zA-Z]{4,8})?)?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Version">
    <xs:annotation>
      <xs:documentation>定义 <b>Version</b> 元素的格式。</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]{1,5})(\.[0-9]{1,5}){0,3}?"/>
    </xs:restriction>
  </xs:simpleType>  

  <xs:complexType name="ContentAppSettings">
    <xs:annotation>
      <xs:documentation>
        定义适用于内容应用程序的设置。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="SourceLocation" type="URLLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>为此内容应用程序指定源文件位置列表。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RequestedWidth" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>以像素为单位指定初始内容占位符的所需宽度，应介于 32 与 1000 之间。</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="32"/>
            <xs:maxInclusive value="1000"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="RequestedHeight" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>以像素为单位指定初始内容占位符的所需高度，应介于 21 与 1000 之间。</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="32"/>
            <xs:maxInclusive value="1000"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TaskPaneAppSettings">
    <xs:annotation>
      <xs:documentation>
        定义适用于任务窗格应用程序的设置。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="SourceLocation" type="URLLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>为此任务窗格应用程序指定源文件位置列表。</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DesktopMailAppSettings">
    <xs:annotation>
      <xs:documentation>
        定义当在台式计算机上运行时适用于邮件应用程序的外观感知设置。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="SourceLocation" type="URLLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>为此桌面邮件应用程序指定源文件位置列表。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RequestedHeight" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>以像素为单位指定当在台式计算机上运行时此邮件应用程序的所需高度，应介于 32 与 450 之间。</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="32"/>
            <xs:maxInclusive value="450"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TabletMailAppSettings">
    <xs:annotation>
      <xs:documentation>
        定义当在 Tablet 计算机上运行时适用于邮件应用程序的外观感知设置。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="SourceLocation" type="URLLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>为此 Tablet 邮件应用程序指定源文件位置列表。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="RequestedHeight" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>以像素为单位指定当在 Tablet 计算机上运行时此邮件应用程序的所需高度，应介于 32 与 450 之间。</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="32"/>
            <xs:maxInclusive value="450"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PhoneMailAppSettings">
    <xs:annotation>
      <xs:documentation>
        定义当在智能手机上运行时适用于邮件应用程序的外观感知设置。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="SourceLocation" type="URLLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>为此电话邮件应用程序指定源文件位置列表。</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Rule" abstract="true">
    <xs:annotation>
      <xs:documentation>
        一种抽象类型，指定主机应用程序激活此邮件应用程序的条件。
      </xs:documentation>
    </xs:annotation>
  </xs:complexType>

  <xs:complexType name="ItemIs">
    <xs:annotation>
      <xs:documentation>
        定义在所选项目属于指定类型时计算结果为 true 的规则。
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="Rule">
        <xs:attribute name="ItemType" type="ItemType" use="required">
          <xs:annotation>
            <xs:documentation>指定要匹配的项目类型。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="ItemClass" type="NonEmptyString" use="optional">
          <xs:annotation>
            <xs:documentation>指定要匹配的项目消息类。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="IncludeSubClasses" type="xs:boolean" use="optional">
          <xs:annotation>
            <xs:documentation>指定如果项目属于指定消息类的子类时规则的计算结果是否应为 true；默认值为 false。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="ItemType">
    <xs:annotation>
      <xs:documentation>
        定义在 <b>ItemIs</b> 规则中使用的不同类型的项目。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Message">
        <xs:annotation>
          <xs:documentation>
            定义邮件消息项目类型。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Appointment">
        <xs:annotation>
          <xs:documentation>
            定义约会项目类型。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="KnownEntityType">
    <xs:annotation>
      <xs:documentation>
        定义可以从项目主题和正文中识别和提取或者可以在 <b>ItemHasKnownEntity</b> 规则中使用的文本模式的名称。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="MeetingSuggestion">
        <xs:annotation>
          <xs:documentation>
            由模式识别进行标识以引用事件或会议的文本。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="TaskSuggestion">
        <xs:annotation>
          <xs:documentation>
            由模式识别进行标识以包含可操作短语的文本。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Address">
        <xs:annotation>
          <xs:documentation>
            由模式识别进行标识以引用美国邮政地址的文本。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Url">
        <xs:annotation>
          <xs:documentation>
            由模式识别进行标识以包含文件名或 Web 地址 URL 的文本。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="PhoneNumber">
        <xs:annotation>
          <xs:documentation>
            由模式识别标识为北美电话号码的一系列数字。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="EmailAddress">
        <xs:annotation>
          <xs:documentation>
            由模式识别进行标识以包含 SMTP 格式电子邮件地址的文本。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Contact">
        <xs:annotation>
          <xs:documentation>
            由模式识别进行标识以包含联系信息的文本。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ItemHasKnownEntity">
    <xs:annotation>
      <xs:documentation>
        定义在项目的主题或正文中包含指定实体类型的文本时计算结果为 true 的规则。
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="Rule">
        <xs:attribute name="EntityType" type="KnownEntityType" use="required">
          <xs:annotation>
            <xs:documentation>指定为使规则求值为 true 而必须找到的实体类型。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="RegExFilter" type="NonEmptyString" use="optional">
          <xs:annotation>
            <xs:documentation>指定要针对激活操作为此实体运行的正则表达式。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="FilterName" type="NonEmptyString" use="optional">
          <xs:annotation>
            <xs:documentation>指定正则表达式筛选器的名称，以便后续可以按代码引用它。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="IgnoreCase" type="xs:boolean" use="optional">
          <xs:annotation>
            <xs:documentation>
              指定当运行 <b>RegExFilter</b> 属性指定的正则表达式时忽略大小写。
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="PropertyName">
    <xs:annotation>
      <xs:documentation>
        定义可以与 <b>ItemHasRegularExpressionMatch</b> 规则配合使用的属性名称。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Subject">
        <xs:annotation>
          <xs:documentation>
            根据项目主题对正则表达式进行求值。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="BodyAsPlaintext">
        <xs:annotation>
          <xs:documentation>
            根据纯文本的项目正文对正则表达式进行求值。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="BodyAsHTML">
        <xs:annotation>
          <xs:documentation>
            如果正文以 HTML 提供，则根据项目正文对正则表达式进行求值。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="SenderSMTPAddress">
        <xs:annotation>
          <xs:documentation>
            根据项目发件人的 SMTP 地址对正则表达式进行求值。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="ItemHasRegularExpressionMatch">
    <xs:annotation>
      <xs:documentation>
        定义当可以在项目的指定属性中找到指定的正则表达式的匹配项时求值为 true 的规则。
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="Rule">
        <xs:attribute name="RegExName" type="NonEmptyString" use="required">
          <xs:annotation>
            <xs:documentation>指定正则表达式的名称，以便后续可以按代码引用它。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="RegExValue" type="NonEmptyString" use="required">
          <xs:annotation>
            <xs:documentation>指定要匹配的正则表达式。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="PropertyName" type="PropertyName" use="required">
          <xs:annotation>
            <xs:documentation>指定要在其中查找匹配项的属性的名称。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="IgnoreCase" type="xs:boolean" use="optional">
          <xs:annotation>
            <xs:documentation>指定当执行正则表达式时忽略大小写。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ItemHasAttachment">
    <xs:annotation>
      <xs:documentation>
        定义在项目包含附件时计算结果为 true 的规则。
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="Rule">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="LogicalOperator">
    <xs:annotation>
      <xs:documentation>
        定义允许将多个规则组合到一个规则集合中的逻辑运算符。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="And">
        <xs:annotation>
          <xs:documentation>
            如果两个操作数都为 true 则返回 true，否则返回 false 的二进制逻辑运算符。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Or">
        <xs:annotation>
          <xs:documentation>
            如果一个或两个操作数为 true 则返回 true，否则返回 false 的二进制逻辑运算符。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="RuleCollection">
    <xs:annotation>
      <xs:documentation>
        定义规则集合以及当对它们进行求值时要使用的逻辑运算符。
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="Rule">
        <xs:sequence>
          <xs:element name="Rule" type="Rule" minOccurs="1" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>指定此集合包含的规则的列表。</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="Mode" type="LogicalOperator" use="required">
          <xs:annotation>
            <xs:documentation>指定当对此规则集合进行求值时要使用的逻辑运算符。</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="AppDomains">
    <xs:annotation>
      <xs:documentation>
        定义应用程序可用于加载其页面的其他域。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="AppDomain" type="LongString">
        <xs:annotation>
          <xs:documentation>
            定义将用于加载一个或多个应用程序页面的域。
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="OfficeApp" abstract="true">
    <xs:annotation>
      <xs:documentation>
        定义适用于 Office 的应用程序的抽象类型。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Id" type="UUID" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定应用程序的唯一 ID。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="AlternateId" type="AlternateId" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>按照 Office 应用商店发布内容指定应用程序的备用 ID。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Version" type="Version" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定应用程序的版本。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ProviderName" type="ShortString" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定开发应用程序的个人或公司的名称。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DefaultLocale" type="CultureName" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定此清单中的字符串使用的区域设置的默认区域性名称。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DisplayName" type="ShortLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定应用程序的简短名称。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Description" type="LongLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定应用程序的更详细的描述。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IconUrl" type="URLLocaleAwareSetting" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定用于表示应用程序的图像的 URL。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SupportUrl" type="URLLocaleAwareSetting" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定提供应用程序支持信息的页面的 URL。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="AppDomains" type="AppDomains" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定此应用程序将用于加载页面的其他域。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="VersionOverrides" xmlns="http://schemas.microsoft.com/office/versionoverrides/1.0" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>包含当应用程序平台的未来版本发布时要使用的元素。 这些元素可能替代为以前定义的元素或新元素。</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="ContentAppCapabilities">
    <xs:annotation>
      <xs:documentation>
        指定可供内容应用程序使用的 Office 应用程序 API 的已命名子集。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Workbook">
        <xs:annotation>
          <xs:documentation>
            此功能代表定义工作簿功能的 API 的子集。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ContentAppCapability">
    <xs:annotation>
      <xs:documentation>
        指定内容应用程序支持的功能。
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="Name" type="ContentAppCapabilities" use="required">
      <xs:annotation>
        <xs:documentation>指定内容应用程序类型支持的功能。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="ContentApp">
    <xs:annotation>
      <xs:documentation>
        定义要嵌入文档内容中以提供更加丰富的基于 Web 的体验的内容应用程序。
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="OfficeApp">
        <xs:sequence>
          <xs:element name="Capabilities" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定内容应用程序所需的功能；如果应用程序至少支持其中的一项功能，则可供应用程序上的用户使用。</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Capability" type="ContentAppCapability" minOccurs="1" maxOccurs="1">
                  <xs:annotation>
                    <xs:documentation>指定内容应用程序所需的功能。</xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="DefaultSettings" type="ContentAppSettings" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定当使用内容应用程序时应用的控制设置。</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Permissions" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>控制可在运行时用于此内容应用程序的 API 的子集；开发人员应基于“最低特权”请求权限。</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Restricted">
                  <xs:annotation>
                    <xs:documentation>
                      应用于所有内容应用程序、启用激活并允许使用 <b>Settings</b> 对象 API 的权限。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="ReadDocument">
                  <xs:annotation>
                    <xs:documentation>
                      包括 <b>Restricted</b> 权限，也使内容应用程序能够使用 <b>getSelectedDataAsync</b> 方法读取文档。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="WriteDocument">
                  <xs:annotation>
                    <xs:documentation>
                      包括 <b>Restricted</b> 权限，也使内容应用程序能够使用 <b>setSelectedDataAsync</b> 方法写入到文档。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="ReadWriteDocument">
                  <xs:annotation>
                    <xs:documentation>
                      包括 <b>ReadDocument</b> 和 <b>WriteDocument</b> 权限，也使内容应用程序能够使用所有写入方法、管理绑定和事件订阅。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="AllowSnapshot" type="xs:boolean" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定当保存主机文档时是否保存此内容应用程序的快照图像。</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:any id="ContentAppSignature" minOccurs="0" maxOccurs="1" namespace="http://www.w3.org/2000/09/xmldsig#" processContents="lax">
            <xs:annotation>
              <xs:documentation>已保留以存储应用程序清单数字签名。</xs:documentation>
            </xs:annotation>
          </xs:any>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Dictionary">
    <xs:annotation>
      <xs:documentation>
        定义实施附加词典支持的应用程序的设置。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="TargetDialects" type="TargetDialects" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定此词典支持的方言。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="QueryUri" type="URLLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定词典查询服务的终结点的 URL。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CitationText" type="ShortLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定此词典的引文样本文字。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DictionaryName" type="ShortLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定此词典的名称。</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DictionaryHomePage" type="URLLocaleAwareSetting" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>指定词典的主页的 URL。</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TargetDialects">
    <xs:annotation>
      <xs:documentation>
        定义此词典支持的方言。
      </xs:documentation>
    </xs:annotation>
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="TargetDialect" type="CultureName">
        <xs:annotation>
          <xs:documentation>
            定义此词典支持的方言，表示为区域性名称字符串。
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="TaskPaneAppCapabilities">
    <xs:annotation>
      <xs:documentation>
        指定可供任务窗格应用程序使用的 Office 应用程序 API 的已命名子集。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Document">
        <xs:annotation>
          <xs:documentation>
            此功能代表定义文档功能的 API 的子集。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Project">
        <xs:annotation>
          <xs:documentation>
            此功能代表定义项目功能的 API 的子集。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Workbook">
        <xs:annotation>
          <xs:documentation>
            此功能代表定义工作簿功能的 API 的子集。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Presentation">
        <xs:annotation>
          <xs:documentation>
            此功能代表定义演示功能的 API 的子集。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TaskPaneAppCapability">
    <xs:annotation>
      <xs:documentation>
        指定任务窗格应用程序支持的功能。
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="Name" type="TaskPaneAppCapabilities" use="required">
      <xs:annotation>
        <xs:documentation>指定任务窗格应用程序类型支持的功能。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TaskPaneApp">
    <xs:annotation>
      <xs:documentation>
        定义任务窗格中显示的、可增强查看和创作体验的应用程序。
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="OfficeApp">
        <xs:sequence>
          <xs:element name="Capabilities" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定任务窗格应用程序所需的功能；如果应用程序至少支持其中的一项功能，则可供应用程序上的用户使用。</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Capability" type="TaskPaneAppCapability" minOccurs="1" maxOccurs="4">
                  <xs:annotation>
                    <xs:documentation>指定任务窗格应用程序所需的功能。</xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="DefaultSettings" type="TaskPaneAppSettings" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定当使用此任务窗格应用程序时应用的控制设置。</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Permissions" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>控制可在运行时用于此任务窗格应用程序的 API 的子集；开发人员应基于“最低特权”请求权限。</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Restricted">
                  <xs:annotation>
                    <xs:documentation>
                      应用于所有任务窗格应用程序、启用激活并允许使用 <b>Settings</b> 对象的权限。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="ReadDocument">
                  <xs:annotation>
                    <xs:documentation>
                      包括 <b>Restricted</b> 权限，也使任务窗格应用程序能够使用 <b>getSelectedAsync</b> 方法读取文档。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="ReadAllDocument">
                  <xs:annotation>
                    <xs:documentation>
                      包括 <b>Restricted</b> 和 <b>ReadDocument</b> 权限，也使任务窗格应用程序能够使用 <b>getAllContentAsync</b> 方法获取整个文档的副本。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="WriteDocument">
                  <xs:annotation>
                    <xs:documentation>
                      包括 <b>Restricted</b> 权限，也使任务窗格应用程序能够使用 <b>setSelectedDataAsync</b> 方法写入到文档。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="ReadWriteDocument">
                  <xs:annotation>
                    <xs:documentation>
                      包括 <b>ReadAllDocument</b> 和 <b>WriteDocument</b> 权限，也使任务窗格应用程序能够使用所有写入方法、管理绑定和事件订阅。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="Dictionary" type="Dictionary" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定应用于实施附加词典支持的任务窗格应用程序的控制设置。</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:any id="TaskPaneAppSignature" minOccurs="0" maxOccurs="1" namespace="http://www.w3.org/2000/09/xmldsig#" processContents="lax">
            <xs:annotation>
              <xs:documentation>已保留以存储应用程序清单数字签名。</xs:documentation>
            </xs:annotation>
          </xs:any>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="MailAppCapabilities">
    <xs:annotation>
      <xs:documentation>
        指定可供邮件应用程序使用的 Office 应用程序 API 的已命名子集。
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Mailbox">
        <xs:annotation>
          <xs:documentation>
            此功能代表定义邮箱功能的 API 的子集。
          </xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="MailAppCapability">
    <xs:annotation>
      <xs:documentation>
        指定邮件应用程序支持的功能。
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="Name" type="MailAppCapabilities" use="required">
      <xs:annotation>
        <xs:documentation>指定邮件应用程序类型支持的功能。</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="MailApp">
    <xs:annotation>
      <xs:documentation>
        定义根据规则进行激活并显示在所选项目附近以增强阅读体验的应用程序。
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="OfficeApp">
        <xs:sequence>
          <xs:element name="Capabilities" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定邮件应用程序所需的功能；如果应用程序至少支持其中的一项功能，则可供应用程序上的用户使用。</xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Capability" type="MailAppCapability" minOccurs="1" maxOccurs="1">
                  <xs:annotation>
                    <xs:documentation>指定所需功能。</xs:documentation>
                  </xs:annotation>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="DesktopSettings" type="DesktopMailAppSettings" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定当在台式计算机上使用此邮件应用程序时应用的控制设置。</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="TabletSettings" type="TabletMailAppSettings" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定当在 Tablet 上使用此邮件应用程序时应用的控制设置。</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="PhoneSettings" type="PhoneMailAppSettings" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定当在智能手机上使用此邮件应用程序时应用的控制设置。</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Permissions" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>控制可在运行时用于此邮件应用程序的 API 的子集；开发人员应基于“最低特权”请求权限。</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Restricted">
                  <xs:annotation>
                    <xs:documentation>
                      适用于所有邮件应用程序、启用 <b>ItemIs</b> 和 <b>ItemHasKnownEntity</b> 激活规则、启用 <b>Settings</b> 对象和 JavaScript API for Office 子集的使用的权限。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="ReadItem">
                  <xs:annotation>
                    <xs:documentation>
                      适用于所选项目，包括 <b>Restricted</b> 权限，并且使邮件应用程序能够使用所有已知的实体和正则表达式激活规则、读取所有属性和写入自定义属性。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="ReadWriteMailbox">
                  <xs:annotation>
                    <xs:documentation>
                      包括所有 <b>ReadItem</b> 权限，也使邮件应用程序能够使用 <b>makeEWSRequestAsync</b> 方法在用户的邮箱中读取和写入任何项目的所有属性。
                    </xs:documentation>
                  </xs:annotation>
                </xs:enumeration>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="Rule" type="Rule" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定应为此邮件应用程序进行求值的激活规则。</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DisableEntityHighlighting" type="xs:boolean" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>指定是否应为此邮件应用程序关闭实体突出显示。</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:any id="MailAppSignature" minOccurs="0" maxOccurs="1" namespace="http://www.w3.org/2000/09/xmldsig#" processContents="lax">
            <xs:annotation>
              <xs:documentation>已保留以存储应用程序清单数字签名。</xs:documentation>
            </xs:annotation>
          </xs:any>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="OfficeApp" type="OfficeApp">
    <xs:annotation>
      <xs:documentation>适用于 Office 的应用程序的清单中的根元素。</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>
