# Generated by Django 5.1.2 on 2025-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_List',
            fields=[
                ('task_id', models.IntegerField(primary_key=1, serialize=False, verbose_name='任务ID')),
                ('task_code', models.CharField(max_length=30, verbose_name='任务工单号')),
                ('task_title', models.CharField(blank=True, max_length=50, verbose_name='任务标题')),
                ('task_level', models.CharField(blank=True, max_length=30, verbose_name='任务重要程度')),
                ('task_status', models.CharField(blank=True, max_length=30, verbose_name='任务状态')),
                ('task_time', models.DateTimeField(blank=True, verbose_name='任务截止日期')),
                ('task_describe', models.TextField(blank=True, verbose_name='任务详情')),
            ],
            options={
                'verbose_name': '任务记录',
                'verbose_name_plural': 'Task_list',
            },
        ),
    ]
