# Generated by Django 5.1.2 on 2025-06-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_List', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_List',
            new_name='Task_Lists',
        ),
    ]
