# Generated by Django 5.1.2 on 2025-06-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_List', '0002_rename_task_list_task_lists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_lists',
            options={'verbose_name': '任务记录', 'verbose_name_plural': '任务记录-Task_list'},
        ),
    ]
