# Generated by Django 5.1.2 on 2025-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Logs',
            fields=[
                ('event_id', models.IntegerField(primary_key=1, serialize=False, verbose_name='故障ID')),
                ('event_code', models.CharField(max_length=30, verbose_name='故障编号')),
                ('event_describe', models.CharField(blank=True, max_length=200, verbose_name='故障描述')),
                ('event_image', models.ImageField(blank=True, upload_to='', verbose_name='故障截图')),
                ('event_level', models.CharField(blank=True, max_length=30, verbose_name='故障评级')),
                ('event_model', models.CharField(blank=True, max_length=30, verbose_name='故障模块')),
                ('event_range', models.CharField(blank=True, max_length=50, verbose_name='故障影响范围')),
                ('event_time', models.DateTimeField(blank=True, verbose_name='故障起止时间')),
                ('event_performance', models.CharField(blank=True, max_length=200, verbose_name='故障表象')),
                ('event_reason', models.TextField(blank=True, verbose_name='故障原因')),
                ('event_solution', models.TextField(blank=True, verbose_name='解决措施')),
            ],
            options={
                'verbose_name': '故障记录',
                'verbose_name_plural': 'Event_log',
            },
        ),
    ]
