# Generated by Django 5.1.2 on 2025-06-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Logs',
            new_name='My_Event_Logs',
        ),
        migrations.AlterModelOptions(
            name='my_event_logs',
            options={'verbose_name': '故障记录', 'verbose_name_plural': '故障记录-Event_log'},
        ),
    ]
