# Generated by Django 5.1.2 on 2025-06-12 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Logs', '0002_rename_event_logs_my_event_logs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_event_logs',
            options={'ordering': ('-event_id',), 'verbose_name': '故障记录', 'verbose_name_plural': '故障记录-Event_log'},
        ),
        migrations.AlterField(
            model_name='my_event_logs',
            name='event_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='故障起止时间'),
        ),
    ]
