# Generated by Django 5.1.2 on 2025-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Logs', '0003_alter_my_event_logs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_event_logs',
            name='event_image',
            field=models.ImageField(blank=True, upload_to='Event_Log/', verbose_name='故障截图'),
        ),
    ]
