# Generated by Django 3.2.24 on 2025-07-21 02:29

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Logs', '0004_alter_my_event_logs_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_event_logs',
            name='event_image',
        ),
        migrations.RemoveField(
            model_name='my_event_logs',
            name='event_performance',
        ),
        migrations.AddField(
            model_name='my_event_logs',
            name='event_title',
            field=models.CharField(default=1, max_length=50, verbose_name='故障标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='my_event_logs',
            name='event_describe',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='描述'),
        ),
    ]
