# Generated by Django 3.2.24 on 2025-09-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Logs', '0005_auto_20250721_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_event_logs',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='my_event_logs',
            name='event_model',
            field=models.CharField(blank=True, choices=[('A', 'MySQL'), ('B', 'Oracle'), ('C', 'PostgreSQL'), ('D', 'Redis'), ('E', 'Cassandra'), ('F', 'Others')], max_length=30, verbose_name='故障模块'),
        ),
    ]
