// msdbg169.idl
/********************************************************
*                                                        *
*   Copyright (C) Microsoft. All rights reserved.        *
*                                                        *
*********************************************************/
cpp_quote("/********************************************************")
cpp_quote("*                                                        *")
cpp_quote("*   Copyright (C) Microsoft. All rights reserved.        *")
cpp_quote("*                                                        *")
cpp_quote("*********************************************************/")
import "oaidl.idl";
import "ocidl.idl";

#ifndef DEBUGGER_PIA_BUILD
import "msdbg.idl";
import "msdbg100.idl";
#endif

#ifdef DEBUGGER_PIA_BUILD
#define XINT32 int
#else
#define XINT32 ULONG32
#endif

// ------------------------------------------------------------------
// IListDebugPortRequests2
[
    object,
    uuid(3444553D-927A-40BA-B256-44BC4F8E678A),
    pointer_default(unique)
]
interface IListDebugPortRequests2 : IUnknown
{
    [propget]
    HRESULT Count([out, retval] XINT32* result);

    [propget, id(DISPID_VALUE), helpstring("property Item")]
    HRESULT Item([in] XINT32 lIndex, [out, retval] IDebugPortRequest2** pRequest);

    HRESULT GetItems(
        [in] XINT32 index,
        [in] XINT32 count,
        [out, size_is(count), length_is(*pCountReturned)] IDebugPortRequest2** itemsArray,
        [in, out] XINT32* pCountReturned);
};

// Optionally implemented by port suppliers which support adding ports. Providing this is an alternative to "EnumPorts"
// for populating the transport qualifier drop down in the Attach to Process dialog.
[
    uuid(0AF3F5A0-057E-45B2-AD74-CE77C31B2A7E),
    version(1.0),
    pointer_default(unique)
]
interface IDebugPortSupplier169 : IUnknown
{
    // Called by the Attach to Process dialog to determine
    // the recently used ports to list.
    HRESULT GetRecentPortRequests(
        [out] IListDebugPortRequests2** ppList
    );
}

