// msdbg165.idl
/********************************************************
*                                                        *
*   Copyright (C) Microsoft. All rights reserved.        *
*                                                        *
*********************************************************/
cpp_quote("/********************************************************")
cpp_quote("*                                                        *")
cpp_quote("*   Copyright (C) Microsoft. All rights reserved.        *")
cpp_quote("*                                                        *")
cpp_quote("*********************************************************/")
import "oaidl.idl";
import "ocidl.idl";

#ifndef DEBUGGER_PIA_BUILD
import "msdbg.idl";
#endif


cpp_quote("#define DBG_EXATTRIB_EXPANSION_HAS_SIDE_EFFECTS  0x0000000000000040")

// Please delete the interface below when adding a new interface
// The interface below is just for generating msdbg165.h
[
    uuid(D2D94AE8-5EE6-4ED2-BCEA-EAE8CBF261FB),
    version(1.0),
    pointer_default(unique),
    local
]
interface IDebugDoNotUseThisInterface165 : IUnknown
{
    // No implementation.
};