// msdbg155.idl
/********************************************************
*                                                        *
*   Copyright (C) Microsoft. All rights reserved.        *
*                                                        *
*********************************************************/
cpp_quote("/********************************************************")
cpp_quote("*                                                        *")
cpp_quote("*   Copyright (C) Microsoft. All rights reserved.        *")
cpp_quote("*                                                        *")
cpp_quote("*********************************************************/")
import "oaidl.idl";
import "ocidl.idl";

#ifndef DEBUGGER_PIA_BUILD
import "msdbg.idl";
#endif

[
	local,
	object,
	uuid(E8111C77-5764-498D-9E48-5F1D37C5B538),
	pointer_default(unique)
]
interface IDebugDocumentContext155 : IUnknown
{    
    // Obtain the bytes of an embedded document, if it exists
    // Returns S_FALSE if an embedded document does not exists
    // The output buffer is allocated using CoTaskMemAlloc, use CoTaskMemFree to free the bytes when finished
    HRESULT GetEmbeddedDocument(
        [out, annotation("_Out_")] ULONG32* pcBytes,
        // NOTE: No 'size_is( , *pcBytes)' attribute here as this is a local interface and adding that causes the PIA scripts to output the wrong managed definition
        [out, annotation("_Outptr_result_buffer_(*pcBytes)")] BYTE** ppBytes
        );
}