// msdbg165.idl
/********************************************************
*                                                        *
*   Copyright (C) Microsoft. All rights reserved.        *
*                                                        *
*********************************************************/
cpp_quote("/********************************************************")
cpp_quote("*                                                        *")
cpp_quote("*   Copyright (C) Microsoft. All rights reserved.        *")
cpp_quote("*                                                        *")
cpp_quote("*********************************************************/")
import "oaidl.idl";
import "ocidl.idl";

#ifndef DEBUGGER_PIA_BUILD
import "msdbg.idl";
#endif

typedef struct _tagDEBUG_ENGINE_METRIC
{
    LPOLESTR metricName;
    VARIANT metricValue;
} DEBUG_ENGINE_METRIC;

[
    object,
    uuid(BB6F6E1A-9862-4B31-B7CD-CD452A84B47F),
    pointer_default(unique)
]
interface IEnumDebugEngineMetrics166 : IUnknown
{
    HRESULT Next([in] ULONG celt, [out, size_is(celt), length_is(*pceltFetched)] DEBUG_ENGINE_METRIC* metrics, [in, out] ULONG* pceltFetched);
    HRESULT Skip([in] ULONG celt);
    HRESULT Reset();
    HRESULT Clone([out] IEnumDebugEngineMetrics166** ppEnum);
    HRESULT GetCount([out] ULONG* pcelt);
}

[
    object,
    uuid(45B79D58-0620-410F-8F39-C7C8C155E36C),
    pointer_default(unique)
]
interface IDebugEngineMetricsUpdatedEvent166 : IUnknown
{
    HRESULT GetUpdatedMetrics([out] IEnumDebugEngineMetrics166** ppMetrics);
}

[
    object,
    uuid(C53F97B4-FBDF-487E-B4C8-23B6EAA4F72D),
    pointer_default(unique)
]
interface IDebugDisconnectableProgram166 : IUnknown
{
    HRESULT CanDisconnect();
    HRESULT Disconnect();
}

