// msdbg1710.idl
/********************************************************
*                                                        *
*   Copyright (C) Microsoft. All rights reserved.        *
*                                                        *
*********************************************************/
cpp_quote("/********************************************************")
cpp_quote("*                                                        *")
cpp_quote("*   Copyright (C) Microsoft. All rights reserved.        *")
cpp_quote("*                                                        *")
cpp_quote("*********************************************************/")
import "oaidl.idl";
import "ocidl.idl";

#ifndef DEBUGGER_PIA_BUILD
import "msdbg.idl";
#endif

#ifdef DEBUGGER_PIA_BUILD
#define XINT32 int
#else
#define XINT32 ULONG32
#endif

// Indicates that the property has an associated source location. The UI can obtain this source location by obtaining the memory context
// (IDebugProperty2.GetMemoryContext), QI'ing for IDebugCodeContext2, and asking the code context for its document context.
cpp_quote("#define DBG_EXATTRIB_CAN_GO_TO_SOURCE 0x0000000000000200")
