// msdbg16A.idl
/********************************************************
*                                                        *
*   Copyright (C) Microsoft. All rights reserved.        *
*                                                        *
*********************************************************/
cpp_quote("/********************************************************")
cpp_quote("*                                                        *")
cpp_quote("*   Copyright (C) Microsoft. All rights reserved.        *")
cpp_quote("*                                                        *")
cpp_quote("*********************************************************/")
import "oaidl.idl";
import "ocidl.idl";

#ifndef DEBUGGER_PIA_BUILD
import "msdbg.idl";
#endif

[
    object,
    uuid(D787DCC6-1873-4F06-B340-0C3E28DD7839),
    pointer_default(unique)
]
interface IDebugStackFrame16A : IUnknown
{
    HRESULT GetInfo(
        [in]  FRAMEINFO_FLAGS dwFieldSpec,
        [in]  DWORD dwFieldSpecEx, // FRAMEINFO_FLAGS_EX as defined in msdbg120.idl
        [in]  UINT nRadix,
        [out] FRAMEINFO* pFrameInfo);
};