/****************************************************************************
*  The TextMgr142 Interfaces
*  Copyright (c) Microsoft Corporation, All Rights Reserved
****************************************************************************/

#ifndef INTEROPLIB

import "oaidl.idl";
import "ocidl.idl";
import "vsshell110.idl"; // for IVsTask

#endif

/****************************************************************************
********    IMPORTANT!!   *********

All guids for interfaces and co-creatable objects in this file should be defined
in textmgruuids.h

****************************************************************************/
#include "textmgruuids.h"
#include "vsshelluuids.h" // for uuid_VsPreserveSigAttribute

////////////////////////////////////////////////////////////////////////////
// IVsExpansionManagerAsync interface
////////////////////////////////////////////////////////////////////////////
[
    uuid(uuid_IVsExpansionManager2),
    version(1.0),
    pointer_default(unique)
]
[custom(uuid_VsPreserveSigAttribute, "preservesig")]
interface IVsExpansionManager2 : IUnknown
{
    HRESULT EnumerateExpansionsAsync(
      [in] GUID guidLang,
      [in] BOOL fShortCutOnly,
      [in, size_is(iCountTypes)] BSTR *bstrTypes,
      [in] long iCountTypes,
      [in] BOOL fIncludeNULLType,
      [in] BOOL fIncludeDuplicates,
      [out] IVsTask **ppTask);
}
