/****************************************************************************
*  The TEXTMGR160 Interfaces
*  Copyright (c) Microsoft Corporation, All Rights Reserved
****************************************************************************/

#ifndef INTEROPLIB

import "context.idl";
import "IVsQueryEditQuerySave2.idl";
import "IVsQueryEditQuerySave80.idl";
import "msxml.idl";
import "textmgr.idl";
import "textmgr2.idl";
import "textmgr100.idl";
import "textmgr110.idl";
import "textmgr120.idl";
import "ImageParameters140.idl";

#endif

/****************************************************************************
********    IMPORTANT!!   *********

All guids for interfaces and co-creatable objects in this file should be defined
in textmgruuids.h

****************************************************************************/

#include "textmgruuids.h"
#include "vsshelluuids.h"

#ifndef INTEROPLIB

[
    uuid(uuid_lib_TextManager160),
    version(1.0)
]
library TextMgr160
{

#endif

    ////////////////////////////////////////////////////////////////////////////
    // Extension of _codewindowbehaviorflags/CODEWINDOWBEHAVIORFLAGS
    ////////////////////////////////////////////////////////////////////////////
    enum _codewindowbehaviorflags2
    {
        //   CWB_DEFAULT = 0x00000000,
        //   CWB_DISABLEDROPDOWNBAR = 0x00000001,
        //   CWB_DISABLESPLITTER = 0x00000002,
        CWB_DISABLEDIFF = 0x00000004,
    };

    ////////////////////////////////////////////////////////////////////////////
    // IVsDropdownBarClient4 interface
    // Adds support for ImageMoniker icons
    //
    ////////////////////////////////////////////////////////////////////////////
    [
        uuid(uuid_IVsDropdownBarClient4)
    ]
    interface IVsDropdownBarClient4 : IUnknown
    {
        // Successor to IVsDropdownBarClient3.GetEntryImage, this method returns an image moniker.
        HRESULT GetEntryImage([in] long iCombo, [in] long iIndex, [out, retval] ImageMoniker* moniker); 
    };

    ////////////////////////////////////////////////////////////////////////////
    // Used as a key for IVsUserData:
    // GUID_EditorDpiContext {E80CBA74-D298-4DB5-A28D-6511675031F4}
    //
    // uint: Sets the DPI context in which the editor instance should be created
    // Valid values for this setting come from __VSDPIMODE
    ////////////////////////////////////////////////////////////////////////////
    cpp_quote("extern const __declspec(selectany) GUID GUID_EditorDpiContext = { 0xe80cba74, 0xd298, 0x4db5, { 0xa2, 0x8d, 0x65, 0x11, 0x67, 0x50, 0x31, 0xf4 } };")

#ifndef INTEROPLIB

};

#endif

