/****************************************************************************
*  The TEXTMGR150 Interfaces
*  Copyright (c) Microsoft Corporation, All Rights Reserved
****************************************************************************/

#ifndef INTEROPLIB

import "context.idl";
import "IVsQueryEditQuerySave2.idl";
import "IVsQueryEditQuerySave80.idl";
import "msxml.idl";
import "context.idl";
import "textmgr.idl";
import "textmgr2.idl";
import "textmgr100.idl";
import "textmgr110.idl";
import "textmgr120.idl";

#endif

/****************************************************************************
********    IMPORTANT!!   *********

All guids for interfaces and co-creatable objects in this file should be defined
in textmgruuids.h

****************************************************************************/

#include "textmgruuids.h"
#include "vsshelluuids.h"

#ifndef INTEROPLIB

[
    uuid(uuid_lib_TextManager150),
    version(1.0)
]
library TextMgr150
{

#endif

    typedef struct _VIEWPREFERENCES4
    {
        //---------------------------------------------------------------------------------------------
        // The following members are copied from the original VIEWPREFERENCES3 struct.  To maintain
        // compatibility, their size, meaning, and order must not be modified.

        // settings for text views
        unsigned fVisibleWhitespace;         // show spaces/tabs etc?
        unsigned fSelectionMargin;           // display selection margin?
        unsigned fAutoDelimiterHighlight;    // allow automatic delimiter highlighting?
        unsigned fGoToAnchorAfterEscape;     // go to anchor after escape?
        unsigned fDragDropEditing;           // drag/drop editing?
        unsigned fUndoCaretMovements;        // include caret movements and text selections in undo list?
        unsigned fOvertype;                  // overtype/insert? - NOT persisted
        unsigned fDragDropMove;              // whether we allow drag/drop moves
        unsigned fWidgetMargin;              // show widget margin?

        // Setting fUserReadOnly to true overrides setting fDragDropEditing and fDragDropMove to true
        unsigned fReadOnly;                  // whether read only
        unsigned fActiveInModalState;        // whether active in a modal state

        unsigned fClientDragDropFeedback;
        unsigned fTrackChanges;
        unsigned uCompletorSize;             
        unsigned fDetectUTF8;
        long     lEditorEmulation;
        unsigned fHighlightCurrentLine;      // highlight current line

        //---------------------------------------------------------------------------------------------
        // End of copy of original VIEWPREFERENCES3 struct.  New members must be added below this point.
        unsigned fShowBlockStructure;        // Show block structure
        unsigned fEnableCodingConventions;   // Enable editor support for coding conventions

    } VIEWPREFERENCES4;

    ////////////////////////////////////////////////////////////////////////////
    // IVsTextManager5 interface
    ////////////////////////////////////////////////////////////////////////////
    [
        uuid(uuid_IVsTextManager5),
        version(1.0)
    ]
    // Preserve signature for method 
    [custom(uuid_VsPreserveSigAttribute, "preservesig")]
    interface IVsTextManager5 : IUnknown
    {
        // For the LANGPREFERENCES member, specify the language in question by setting 
        // pLangPrefs->guidLang to the language SID.
        [local] HRESULT GetUserPreferences5(
            [out]     VIEWPREFERENCES4      * pViewPrefs,  // struct is caller-allocated
            [in, out] LANGPREFERENCES3      * pLangPrefs,  // struct is caller-allocated
            [in, out] FONTCOLORPREFERENCES2 * pColorPrefs);// struct is caller-allocated

        [local]  HRESULT SetUserPreferences5(
            [in] const VIEWPREFERENCES4      * pViewPrefs,
            [in] const LANGPREFERENCES3      * pLangPrefs,
            [in] const FONTCOLORPREFERENCES2 * pColorPrefs);
    };

    ////////////////////////////////////////////////////////////////////////////
    // IVsTextManagerEvents5 interface
    ////////////////////////////////////////////////////////////////////////////
    [
        uuid(uuid_IVsTextManagerEvents5 ),
        version(1.0)
    ]
    // Preserve signature for method 
    [custom(uuid_VsPreserveSigAttribute, "preservesig")]
    interface IVsTextManagerEvents5 : IUnknown
    {

        // Fired when the user's global preferences have changed
        [local]  HRESULT OnUserPreferencesChanged5([in] const VIEWPREFERENCES4  * pViewPrefs,
            [in] const LANGPREFERENCES3  * pLangPrefs,
            [in] const FONTCOLORPREFERENCES2 * pColorPrefs);
    };

#ifndef INTEROPLIB

};

#endif

