//  Copyright (c) Microsoft Corporation. All Rights Reserved.

#ifndef INTEROPLIB
import "oaidl.idl";

// done because the .idl file does not understand namespaces but these interfaces are in a namespace in the header file.
cpp_quote("#include \"dte.h\"")
cpp_quote("#ifdef FORCE_EXPLICIT_DTE_NAMESPACE")
cpp_quote("#define DTE VxDTE::DTE")
cpp_quote("#define Project VxDTE::Project")
cpp_quote("#define ProjectItem VxDTE::ProjectItem")
cpp_quote("#endif")

// Interface definitions
cpp_quote("#define VSLANGPROJ165_VER_MAJ   16")
cpp_quote("#define VSLANGPROJ165_VER_MIN    5")

#define VSLANGPROJ_VER        16.5

[
    uuid(ab78db14-5876-4723-ac5a-574434a255ad),
    helpstring("Microsoft Visual Studio Project Model (16.5)"),
    version(VSLANGPROJ_VER)
]
library VSLangProj165
{
#endif // INTEROPLIB

    importlib("vslangproj110.tlb");

    enum VsProjPropId165
    {
        VBPROJPROPID_AuthenticationMode = 17310,
    };

    typedef [uuid(584258e0-b43e-40d7-b74c-a6a0a9a6468a)]
    enum AuthenticationMode
    {
        AuthenticationMode_None,
        AuthenticationMode_Windows,
        AuthenticationMode_Universal,
    }
    AuthenticationMode;

    [
        uuid(b0e31b9f-7b07-4af7-802c-780fb8e01acb),
        helpstring("VB project configuration properties 7"),
        pointer_default(unique),
        dual
    ]
    interface VBProjectConfigurationProperties7 : VBProjectConfigurationProperties6
    {
        [propget, id(VBPROJPROPID_AuthenticationMode), helpstring("Authentication Mode")]
        HRESULT AuthenticationMode([out, retval] AuthenticationMode* pValue);
        [propput, id(VBPROJPROPID_AuthenticationMode), helpstring("Authentication Mode")]
        HRESULT AuthenticationMode([in] AuthenticationMode value);
    }

    [
        uuid(7ff6c112-6bc3-4b3e-93e5-029443efcf85),
        helpstring("C# project configuration properties 7"),
        pointer_default(unique),
        dual
    ]
    interface CSharpProjectConfigurationProperties7 : CSharpProjectConfigurationProperties6
    {
        [propget, id(VBPROJPROPID_AuthenticationMode), helpstring("Authentication Mode")]
        HRESULT AuthenticationMode([out, retval] AuthenticationMode* pValue);
        [propput, id(VBPROJPROPID_AuthenticationMode), helpstring("Authentication Mode")]
        HRESULT AuthenticationMode([in] AuthenticationMode value);
    }

#ifndef INTEROPLIB
}
#endif

cpp_quote("#ifdef FORCE_EXPLICIT_DTE_NAMESPACE")
cpp_quote("#undef DTE")
cpp_quote("#undef Project")
cpp_quote("#undef ProjectItem")
cpp_quote("#endif")
