/****************************************************************************
*  The VSSHELL Interfaces
*  Copyright (c) Microsoft Corporation, All Rights Reserved
****************************************************************************/

#ifndef INTEROPLIB

// Imports - all imports should go here (inside the ifndef)

import "oaidl.idl";
import "vsshell.idl";
import "vsshell2.idl";
import "vsshell80.idl";
import "vsshell90.idl";
import "vsshell100.idl";
import "vsshell110.idl";
import "vsshell120.idl";
import "vsshell140.idl";
import "vsshell150.idl";
import "objext.idl";
import "olecm.idl";
import "VsPlatformUI.idl";
import "basetsd.h";
import "oleidl.idl";
import "servprov.idl";
import "docobj.idl";
import "designer.idl";
import "textmgr.idl";
import "oleipc.idl";
import "uilocale.idl";

#endif

#include "vscookie.h"

/****************************************************************************

***** General notes for updating this file

***** Proxy Stub

If you modify anything in here, you may need to rebuild the proxy-stub,
msenvXXXp.dll, and update its registration file,
SetupAuthoring\env\Registry\msenvXXXp.ddr. To do that, once this file has been
built and published, build from env\msenv\proxies and observe the build output.

If you need to omit something from the proxy/stub file, then put it inside an
#ifndef PROXYSTUB_BUILD/#endif block

There is no need to define GUIDs in external header files such as
vsshelluuids.h. Instead, define the GUID directly within the [uuid(...)]
attribute and use __uuidof in native code.

***** Primary Interop Assemblies

If you modify anything in here, you may need to rebuild the primary interop
assemblies. To do that, once this file has been built and published, build
from vscommon\pias using: 'msbuild pias.nativeproj'

***** PreserveSig

Prefer "nopreservesig", which is the default for all new interfaces, because
it creates cleaner managed code. Managed implementations are free to throw
exceptions which will automatically be translated to HRESULTs in the CLR's
COM interop layer. Native implementations will return HRESULTs and they will
be converted to exceptions for managed callers.

Do not create methods returning S_FALSE. Instead use an additional
"[out] VARIANT_BOOL*" or "[out,retval] VARIANT_BOOL*" argument.

***** Interface inheritance

You may derive new interfaces from existing ones, but avoid mixing
"preservesig" (old) with "nopreservesig" (new). Derive from an older interface
if all of the methods in your interface match the preservesig attributes of the
older interface.

Remember, when implementing a derived interface in C++, you must implement
QueryInterface for the base interface(s) too.

***** Enumerators and bitwise flags passed as parameters:

When a parameter must be exactly one of a set of values (a true enumerator),
the values should be defined and used as follows:

typedef enum __VSSAMPLETYPE
{
ST_THISTYPE     = 0,   // first value should be zero or one, except
ST_THATTYPE     = 1,   // in special cases, and following values
ST_THEOTHERTYPE = 2,   // should use consecutive numbers
} VSSAMPLETYPE;

interface IVsSample : IUnknown
{
HRESULT SampleMethod([in] VSSAMPLETYPE stType);
}

When a parameter must be exactly one of a set of values (a true enumerator),
and is considered a PROPID, the values should be defined and used as follows:

enum __VSSAMPLEPROPID
{
VSSAMPPROPID_LAST     = -7000,  // first value should be a unique
VSSAMPPROPID_This     = -7000,  // number not used by any other
VSSAMPPROPID_That     = -7001,  // PROPID, and following values
VSSAMPPROPID_FIRST    = -7001,  // should use consecutive numbers
};
typedef LONG VSSAMPLEPROPID;

interface IVsSample : IUnknown
{
HRESULT GetProperty([in] VSSAMPLEPROPID propid, [out,retval] VARIANT *pvar);
HRESULT SetProperty([in] VSSAMPLEPROPID propid, [in] VARIANT var);
}

When a parameter can be none of or a combination of values (bitwise),
the values should be defined and used as follows:

enum __VSSAMPLEOPTS
{
SO_THISOPTION     = 0x00000001,   // first value should be one,
SO_THATOPTION     = 0x00000002,   // following values should use
SO_THEOTHEROPTION = 0x00000004,   // consecutive powers of two
};
typedef DWORD VSSAMPLEOPTS;

interface IVsSample : IUnknown
{
HRESULT SampleMethod([in] VSSAMPLEOPTS grfOptions);
}

***** Defining properties

Define properties as follows:

interface IVsSample : IUnknown
{
[propget] HRESULT Foo([out, retval] BSTR *pbstrFoo);
[propput] HRESULT Foo([in] LPCOLESTR strFoo);
}

Using [propget], [propput] and [out, retval] makes the interface easier
to implement and consume in managed code.

Note: The example above shows a case where the get/put methods accept slightly different
argument types (BSTR versus LPCOLESTR). As long as the equivalent interop types are the
same, this is fine (MarshalAs[..] attributes will be added as necessary). However, this
is typically seen only for string arguments.

***** Array typed args

Pass array type arguments (both in and out) using [] and size_is when the corresponding
size argument is present. You must have the array size as an argument for interop to
work correctly.

interface IVsSample : IUnknown
{
HRESULT MethodPassesInArray([in] int cItems, [in, size_is(cItems)] int prgiItems[]);
}

DO NOT use [in] int piItems[].

For simple element types, consider using SAFEARRAY: e.g. SAFEARRAY(VARIANT_BOOL),
SAFEARRAY(BSTR), SAFEARRAY(INT), etc. because they interop cleanly to managed code, but
note that there is additional memory allocation and it may not be appropriate for high-
performance methods. Also see the following note.

******* SAFEARRAY(IVsFoo*)

SAFEARRAY(IVsFoo*) will cause MIDL warning 2456:
SAFEARRAY(interface pointer) doesn't work using midl generated proxy

If you know for sure that implementions will never will never need to be called cross
apartment (cross thread/process), then you can add [local] to the method.

Alternatively, consider creating a custom IEnumXXX interface.

****** Strings

Use "[in] LPCOLESTR" instead of "[in] BSTR"

for faster marshaling and more convenience to native callers.
(But continue to use "[out] BSTR*" for out args.)

Generally, you don't need to specify [in,string] for NUL-terminated strings
because most of the "pointer to character" typedefs are already attributed with
[string]. (e.g. "typedef [string] const OLECHAR *LPCOLESTR")

******* Boolean

Use VARIANT_BOOL instead of BOOL because it interops as System.Boolean instead
of System.Int

However, exercise caution when assigning or comparing to/from C++ bool in native
code because VARIANT_BOOL is typedef'd as a short and VARIANT_TRUE is ((short)-1)

******* Optional (may be null) args

Use [in,unique] for optional input arguments which may be NULL.
Note that pointer_default(unique) does NOT do this automatically.

Do not use [out,unique] because unique cannot be applied to [out]-only top-level
pointer parameters. However, you can use [in,out,unique].

Do not use [optional]. It only works with VARIANT anyway and it's not
obvious for managed coders.

******* [out] NonNullableType*

Note that arguments of the type "[out] Foo* pFoo", where Foo is a "non-nullable
type" such as int, double, VARIANT_BOOL, BSTR, will be converted to
"out Foo[] pFoo" in managed code. This is a non-standard conversion applied by
an IL transformation step during the build for the interop assembly.

******* Service GUIDs

Define service GUIDs via an empty interface derived from IUnknown
and put it inside an #ifndef PROXYSTUB_BUILD/#endif block

******* HWNDs, HANDLE, and other non-marshalable types

Take care if you define an interface with HWND, HGDIOBJ or other Win32
handle types. These typically need to be marked [local] since they
cannot cross apartment (specifically, process) boundaries.

******* WPARAM, LPARAM, LRESULT, *_PTR types

Currently any of the types listed above is translated incorreclty in to PIA. As all of them
are pointer types, we want them to be IntPtr type but PIA generation uses int32 or int64 based on
build architecture so it is suggested to use "HANDLE" type when INTEROPLIB is defined.

TODO: Figure out how to properly build these types in both header, typelib and interop.

****************************************************************************/

#include "vsshelluuids.h" // for uuid_VsPreserveSigAttribute

// forward declarations

// enum __VSDBGLAUNCHFLAGS160 ADDED IN DEV16 RTW
// NOTE: USE OF THIS ENUM REQUIRES DEV16 RTW
enum __VSDBGLAUNCHFLAGS160
{
    /********************************************** defined in vsshell.idl
    DBGLAUNCH_Silent                = 0x00000001,
    DBGLAUNCH_LocalDeploy           = 0x00000002, // passed to IVsDebuggableProjectCfg::Launch to allow optimizations
    DBGLAUNCH_NoDebug               = 0x00000004, // launch without attaching a debugger
    DBGLAUNCH_DetachOnStop          = 0x00000008, // detach instead of terminate when debugging stopped.
    DBGLAUNCH_Selected              = 0x00000010, // launch selected project instead of startup project
    DBGLAUNCH_StopDebuggingOnEnd    = 0x00000020, // when this process ends, debugging is stopped.
    DBGLAUNCH_WaitForAttachComplete = 0x00000040, // when DLO_LaunchByWebServer, wait for the attach to finish before continuing to launch other targets
    **********************************************  defined in vsshell80.idl*/
    /*
    DBGLAUNCH_MergeEnv              = 0x00000080, // provided environment should be merged with system environment
    DBGLAUNCH_DesignTimeExprEval    = 0x00000100, // launched for design-time expression evaluation
    DBGLAUNCH_StopAtEntryPoint      = 0x00000200, // Stop at the entrypoint (step-into)
    DBGLAUNCH_CannotDebugAlone      = 0x00000400, // this process cannot be debugged alone -- stop debugging when only processes with this flag remain
    **********************************************/
    /********************************************** defined in vsshell90.idl
    DBGLAUNCH_WaitForEvent          = 0x00000800  // Debugger should wait for a named event to become signaled after launching the first debug target and before launching more targets
    **********************************************/
    /********************************************** defined in vsshell90.idl (SP1)
    DBGLAUNCH_UseDefaultBrowser     = 0x00001000  // Debugger should use the Default Web Browser; this flag used in conjunction with DLO_LaunchBrowser.
    // The default browser is obtained via IVsUIShellOpenDocument:: GetFirstDefaultPreviewer().
    // The bstrEXE in VsDebugTargetInfo2 points to the URL to be launched. Web Site projects will use
    // this for Silverlight projects. This allows, for example, Firefox to be used which is single
    // instance and so has to be handled differently on launch. Other project systems (e.g. C++) that
    // currently use DLO_LaunchBrowser will continue to use that and IE will get launched as before.
    **********************************************/
    /********************************************* defined in vsshell100.idl (dev10)
    DBGLAUNCH_PrepForDebug          = 0x00002000, // We will eventually debug this process, so allow the debugger to perform additional setup
    DBGLAUNCH_TerminateOnStop       = 0x00004000, // Terminate the debuggee when debugging is stopped. It is an error to specify both this and DBGLAUNCH_DetachOnStop
    DBGLAUNCH_BreakOneProcess       = 0x00008000  // Disable 'Break all processes when one process breaks' debugger option for the debugging session; this option is ignoring if debugging has already started.

    DBGLAUNCH_BlockCredentialsDialog= 0x00010000, // Blocks the creditials dialog from being shown on authentication errors
    DBGLAUNCH_BlockWWSDialog        = 0x00020000, // Blocks the WWS install dialog from being shown
    DBGLAUNCH_StartInSimulator      = 0x00040000  // For DLO_AppPackageDebug, debugger should launch the application (or expect the application to start) in the simulator
    ********************************************** defined in vsshell110.idl (dev11)
    **********************************************/
    /********************************************* defined in vsshell120.idl (dev12)
    DBGLAUNCH_ALLOW_EVENTS_AFTER_STOPPED    = 0x00080000,  // Allows stopping events in break-mode
    DBGLAUNCH_FORCE_32BIT_DEBUG             = 0x00100000,  // Force use of the 32-bit debugger (currently used only for DLO_CreateProcess)
    DBGLAUNCH_FORCE_64BIT_DEBUG             = 0x00200000   // Force use of the 64-bit debugger (currently used only for DLO_CreateProcess)
    ********************************************** defined in vsshell130.idl (dev13)
    **********************************************/
    /********************************************** defined in vsshell140.idl (dev14)
    DBGLAUNCH_ContainsStartupTask           = 0x00400000,  // Use Startup Task activator (currently used only for DLO_AppPackageDebug)
    DBGLAUNCH_Profiling                     = 0x00800000   // Launch process for profiling
    **********************************************/
    /********************************************** defined in vsshell142.idl (dev14)
    DBGLAUNCH_NoTerminateOnImmediateLaunch = 0x01000000   // For DLO_AppPackageDebug, allow app to be running immediately after App Activation.
    **********************************************/
    /********************************************** defined in vsshell154.idl (dev154)
    DBGLAUNCH_ParallelLaunch = 0x02000000
    **********************************************/
    /********************************************** defined in vsshell1548idl (dev158)
    DBGLAUNCH_ForcePseudoRemoteDebug = 0x04000000, // Force usage of a separate debugger worker process (msvsmon.exe) for local debugging
    DBGLAUNCH_IntegratedConsole = 0x08000000 // Application should be launched using the VS integrated console
    **********************************************/
    DBGLAUNCH_BypassAttachSecurity = 0x10000000
};
typedef DWORD VSDBGLAUNCHFLAGS160;

// enum __VSSEARCHPLACEMENT2 ADDED IN DEV16 RTW
// NOTE: USE OF THIS ENUM REQUIRES DEV16 RTW
enum __VSSEARCHPLACEMENT2
{
    /********************************************* defined in vsshell110.idl (dev11)
    SP_NONE = 0,         // The search is not setup for the window
    SP_DYNAMIC = 1,      // The search control has placement in the shell-owned frame area and the shell adjusts dynamically the control's location and size depending on toolbars number, window size, etc.
    SP_STRETCH = 2,      // The search control has placement in the shell-owned frame area, below the top toolbars (if any), on its own row, stretching the frame width.
    SP_CUSTOM = 3,       // The window has a search host associated, but the search control does not have placement in the shell-owned frame area
    **********************************************/
    SP_DYNAMIC_LEFT = 4  // The search control has left placement in the shell-owned frame area and the shell adjusts dynamically the control's location and size depending on toolbars number, window size, etc.
};

//----------------------------------------------------------------------
// IVsToolWindowToolbarHost4
//
// This is intended for new method signatures that are compatible with both 32 and 64 bit interop
//
//----------------------------------------------------------------------
[
    uuid(4d6ca502-1fb1-4a49-81c7-8d2d423f7f0f),
    version(1.0),
    pointer_default(unique),
    local,
    custom(uuid_VsPreserveSigAttribute, "preservesig")
]
interface IVsToolWindowToolbarHost4 : IUnknown
{
    HRESULT ProcessMouseActivation2(
        [in] HWND hwnd,
        [in] UINT msg,
#ifndef INTEROPLIB
        [in] WPARAM wp,
        [in] LPARAM lp);
#else
        [in] HANDLE wp,
        [in] HANDLE lp);
#endif

    // Same as ProcessMouseActivation, but for modal windows/dialogs containing
    //  toolbars.    If this method returns S_FALSE, the caller should return from
    //  its WndProc immediately with the value stored   in plResult. Otherwise the
    //  caller should   process it as it normally does.  There is no harm in a
    //  non-modal   tool window calling this function, as it is a safe superset of
    //  the functionality   in ProcessMouseActivation.
    HRESULT ProcessMouseActivationModal2(
        [in] HWND   hwnd,
        [in] UINT   msg,
#ifndef INTEROPLIB
        [in] WPARAM wp,
        [in] LPARAM lp,
        [out] LRESULT *plResult);
#else
        [in] HANDLE wp,
        [in] HANDLE lp,
        [out] HANDLE *plResult);
#endif

};

// IVsServiceInfo2
// Represents information about a VS service.
// Implementation must be free-threaded.
//----------------------------------------------------------------------------
[
    uuid(0161283a-d9b6-4c8e-8c9b-121d0e413dd1),
    pointer_default(unique)
]
interface IVsServiceInfo2 : IUnknown
{
    [propget] HRESULT IsFreeThreaded([out, retval] VARIANT_BOOL *pIsFreeThreaded);
    [propget] HRESULT IsCacheable([out, retval] VARIANT_BOOL *pIsCacheable);
}

//-----------------------------------------------------------------------------
// SVsBuiltInServiceInfoQueryService
// The service for the IVsServiceInfoQueryService service that handles built-in
// (i.e. non-registered) services.
//-----------------------------------------------------------------------------
[
    uuid(11d239a8-47cd-4fac-9841-d4c0e1e4b5f4)
]
interface SVsBuiltInServiceInfoQueryService : IUnknown
{
}
cpp_quote("#define SID_SVsBuiltInServiceInfoQueryService IID_SVsBuiltInServiceInfoQueryService")

//----------------------------------------------------------------------------
// IVsPackageInfo
// Represents information about a VS package.
// Implementation must be free-threaded.
//----------------------------------------------------------------------------
[
    uuid(9248b73c-1a06-414e-a926-9fea3f38a375),
    pointer_default(unique),
]
interface IVsPackageInfo : IUnknown
{
    [propget] HRESULT Name([out, retval] BSTR *name);
    [propget] HRESULT Id([out, retval] GUID *id);
    [propget] HRESULT ProductName([out, retval] BSTR *productName);
    [propget] HRESULT CompanyName([out, retval] BSTR *companyName);
    [propget] HRESULT IsBackgroundLoadSafe([out, retval] VARIANT_BOOL *isBackgroundLoadSafe);
    [propget] HRESULT IsLoaded([out, retval] VARIANT_BOOL *isLoaded);
}

//-----------------------------------------------------------------------------
// IVsPackageInfoQueryService
// A service that exposes information about a package
// Implementation must be free-threaded.
//-----------------------------------------------------------------------------
[
    uuid(1669c91d-923e-4cfe-82c5-e99075abb0ef),
    pointer_default(unique),
]
interface IVsPackageInfoQueryService : IUnknown
{
    HRESULT GetPackageInfo([in] REFGUID packageGuid, [out, retval] IVsPackageInfo **ppPackageInfo);
}

//-----------------------------------------------------------------------------
// SVsPackageInfoQueryService
// The service id for the VS service that implements IVsPackageInfoQueryService
//-----------------------------------------------------------------------------
[uuid(b5477757-d697-4dfe-a8ef-04e2992f7d26)]
interface SVsPackageInfoQueryService : IUnknown
{
}
cpp_quote("#define SID_SVSPackageInfoQueryService IID_SVsPackageInfoQueryService")

//----------------------------------------------------------------------------
// IVsToolboxClipboardCycler2
//----------------------------------------------------------------------------
// Implemented by the Environment.
// Interface retrieved by QueryService(SID_SVsToolbox, IID_IVsToolboxClipboardCycler2,...).
// Used by editors that participate with the Clipboard Ring by handling the
// CLSID_StandardCommandSet97/ShowClipboardHistory command.
[
    uuid(3ED19650-63FE-440E-A3D2-87BC421B04D2),
    version(1.0),
    pointer_default(unique),
    custom(uuid_VsPreserveSigAttribute, "preservesig")
]
interface IVsToolboxClipboardCycler2 : IVsToolboxClipboardCycler
{
    /*
    Return the number of items currently present in the toolbox clipboard
    */
    HRESULT GetCountOfClipboardItems([in] IVsToolboxUser *pTarget, [out] UINT *pLength);
};

[
    uuid(CF43601B-FA34-4CCB-8C81-436566368517),
    version(1.0),
    pointer_default(unique)
]
[custom(uuid_VsPreserveSigAttribute, "preservesig")]
interface IVsFontAndColorStorage4 : IVsFontAndColorStorage3
{
    HRESULT GetFont(
        [in] HWND hwnd,
        [in, out] LOGFONTW *pLOGFONT,
        [in, out] FontInfo *pInfo);
}

enum __VSSPROPID10
{
    // See previous version of vsshellXX.idl for previous enumeration values.
    VSSPROPID_GlobalRestoreSolutionExplorerStateOption = -9085, // BOOL VARIANT_TRUE if we restore solution explorer state, else VARIANT_FALSE. True by default

    // !!!! NOTE !!!!   THIS MUST BE THE SAME AS THE LAST PROP DEFINED
    // when this is extended in the next version idl, uses of it must be changed to the new value
    VSSPROPID_FIRST10 = -9085
};

cpp_quote("extern const __declspec(selectany) GUID UICONTEXT_SolutionClosing = {0xda9f8018, 0x6ea4, 0x48df, {0xbd, 0xb6, 0xb8, 0x5a, 0xbd, 0x8f, 0xc5, 0x1e}};")

//The data used as an identifier in the command table for the purpose of looking up information
typedef struct _VSCOMMANDID
{
    GUID  CommandSet;
    DWORD CommandId;
}VSCommandId;

//----------------------------------------------------------------------------
// IVsInvalidateCachedCommandState
// A free-threaded alternative to IVsUIShell::UpdateCommandUI
//----------------------------------------------------------------------------
[
    uuid(0a026971-5a0e-45c9-9479-e62ab18b7de6),
    version(1.0),
    pointer_default(unique),
]
interface IVsInvalidateCachedCommandState : IUnknown
{
    // Invalidate ALL state for all commands in VS. Essentially a free-threaded version of
    // IVsUIShell::UpdateCommandUI. The update is always asynchronous and this method simply
    // marks it as needed and returns.
    HRESULT InvalidateCommandUIState();

    // Invalidates cached status for just one single command.
    HRESULT InvalidateSpecificCommandUIState(VSCommandId command);
};

//-----------------------------------------------------------------------------
// SVsInvalidateCachedCommandState
// The service type identifying the free-threaded command cache invalidation service
//-----------------------------------------------------------------------------
[uuid(74590f40-42ef-4df4-b762-902b09884657)]
interface SVsInvalidateCachedCommandState : IUnknown
{
}
cpp_quote("#define SID_SVsInvalidateCachedCommandState IID_SVsInvalidateCachedCommandState")


//----------------------------------------------------------------------------
// IVsUIContextEvents
// An event raised when a UI context goes from active / inactive (or vice-versa).
// This is allow free-threaded sign-ups for these events on IVsUIContextMonitor.
//----------------------------------------------------------------------------
[
    uuid(0393d191-94ac-4997-9310-2eac67495816),
    version(1.0),
    pointer_default(unique),
]
interface IVsUIContextEvents : IUnknown
{
    HRESULT OnContextChanged([in] GUID uiContext, [in] VARIANT_BOOL active);
};

//----------------------------------------------------------------------------
// Free-threaded service that allows read-only type access to UI context state
// and events to monitor changes to it.
//----------------------------------------------------------------------------
[
    uuid(2b663830-25e6-4a21-94a3-24322fa4f01d),
    version(1.0),
    pointer_default(unique),
]
interface IVsUIContextMonitor : IUnknown
{
    // This can optionally be checked to determine if UI contexts are even available. They won't be available, for instance,
    // when doing a command line build in the shell, during update configuration, etc...
    HRESULT AreUIContextsAvailable([out, retval] VARIANT_BOOL *pfAvailable);

    // Tests if the UI context is active or not
    HRESULT IsUIContextActive([in] GUID uiContext, [out, retval] VARIANT_BOOL *pfActive);

    // Advise for UI context activation status changed events
    HRESULT AdviseContextEvents([in] IVsUIContextEvents *callback, [out, retval] VSCOOKIE *cookie);

    // Unadvise from UI context activation status changed events
    HRESULT UndaviseContextEvents([in] VSCOOKIE cookie);
};

cpp_quote("struct __declspec(deprecated(\"IVsUIContextMonitor is deprecated, please use IVsUIContextManager.\")) IVsUIContextMonitor;")

// {8F0F3ED3-2241-4638-95CE-D8D5C5222C1D}
cpp_quote("extern const __declspec(selectany) GUID UICONTEXT_DocumentWindowActive = { 0x8f0f3ed3, 0x2241, 0x4638, { 0x95, 0xce, 0xd8, 0xd5, 0xc5, 0x22, 0x2c, 0x1d } };")
// {30840431-1832-47A3-94A4-64E5EC71B0CD}
cpp_quote("extern const __declspec(selectany) GUID UICONTEXT_ToolWindowActive = { 0x30840431, 0x1832, 0x47a3, { 0x94, 0xa4, 0x64, 0xe5, 0xec, 0x71, 0xb0, 0xcd } };")

//-----------------------------------------------------------------------------
// SVsUIContextMonitor
// The service type identifying the free-threaded service that exposes the immutable
// bits of UI context (i.e. map from GUID -> VSCOOKIE, asking if it is active
// advising/unadvising for events)
//-----------------------------------------------------------------------------
[uuid(63b07ba0-b399-4b71-aa69-0d97c097b69c)]
interface SVsUIContextMonitor : IUnknown
{
}
cpp_quote("#define SID_SVsUIContextMonitor IID_SVsUIContextMonitor")

//----------------------------------------------------------------------------
// VSDPIMODE
//----------------------------------------------------------------------------
// These are used for declaring the supported DPI awareness mode.
enum __VSDPIMODE
{
    VSDM_Unaware    = 0x01,
    VSDM_System     = 0x02,
    VSDM_PerMonitor = 0x03,
};

typedef DWORD VSDPIMODE;

//----------------------------------------------------------------------------
// IVsDpiAware
//----------------------------------------------------------------------------
// Implemented by objects that want to control which DPI awareness context in
// which their UI is created. Only tool windows/designers/editors with Win32
// and/or WinForms content need to use this interface; if the content is WPF,
// this interface is not needed.
//
// For tool windows this should be implemented in the same place IVsWindowPane
// or IOleObject is implemented such as on a native tool window class, or by
// the managed class that derives from ToolWindowPane.
//
// For designers the implementation location is TBD.
[
    uuid(2283D00F-C00F-405E-8C23-8D31CC714FDD),
    version(1.0),
    pointer_default(unique)
]
interface IVsDpiAware : IUnknown
{
    [propget] HRESULT Mode([out, retval] VSDPIMODE *dwMode);
};

//----------------------------------------------------------------------------
// IUIHostLocale3
//----------------------------------------------------------------------------
[
    uuid(2C2EA033-02BE-11d1-8C85-00C04FC2AA89),
    version(1.0),
    custom(uuid_VsPreserveSigAttribute, "preservesig")
]
interface IUIHostLocale3 : IUIHostLocale2
{
    HRESULT GetDialogFontEx([in] HWND hwnd,
                          [out] UIDLGLOGFONT *plogfont);
};
