//=----------------------------------------------------------------------------
// Microsoft Visual Studio
//
// Microsoft Confidential
// Copyright (c) Microsoft Corporation.  All Rights Reserved.
//
// File:     VSShell175.idl
//
//
// Current Owner:
//=----------------------------------------------------------------------------
////////////////////////////////////////////////////////////////////////////////

#include "vsshelluuids.h" // for uuid_VsPreserveSigAttribute

#ifndef INTEROPLIB

// Imports - all imports should go here (inside the ifndef)

import "oaidl.idl";
import "ocidl.idl";
import "context.idl";
import "vsshell.idl";
import "vsshell2.idl";
import "vsshell80.idl";
import "vsshell90.idl";
import "vsshell100.idl";
import "vsshell110.idl";
import "vsshell120.idl";
import "vsshell140.idl";
import "vsshell150.idl";
import "vsshell153.idl";
import "vsshell155.idl";
import "vsshell156.idl";
import "vsshell157.idl";
import "vsshell158.idl";
import "vsshell160.idl";
import "vsshell161.idl";
import "vsshell162.idl";
import "vsshell169.idl";
import "vsshell1610.idl";
import "VsPlatformUI.idl";


// Excluding DTE related includes for C builds as they contain C++ only constructs
// and they produce compile errors while building the proxy DLL (msenvXXXp).
cpp_quote("#ifdef __cplusplus")
cpp_quote("#include \"dte.h\"")
cpp_quote("#include \"textmgr2.h\"")
cpp_quote("#include \"guiddef.h\"")
cpp_quote("#endif // __cplusplus")

#endif

// enum __VSDBGLAUNCHFLAGS175 ADDED IN DEV17.5 Preview 1
// NOTE: USE OF THIS ENUM REQUIRES DEV17.5 Preview 1
enum __VSDBGLAUNCHFLAGS175
{
    /********************************************** defined in vsshell.idl
    DBGLAUNCH_Silent                = 0x00000001,
    DBGLAUNCH_LocalDeploy           = 0x00000002, // passed to IVsDebuggableProjectCfg::Launch to allow optimizations
    DBGLAUNCH_NoDebug               = 0x00000004, // launch without attaching a debugger
    DBGLAUNCH_DetachOnStop          = 0x00000008, // detach instead of terminate when debugging stopped.
    DBGLAUNCH_Selected              = 0x00000010, // launch selected project instead of startup project
    DBGLAUNCH_StopDebuggingOnEnd    = 0x00000020, // when this process ends, debugging is stopped.
    DBGLAUNCH_WaitForAttachComplete = 0x00000040, // when DLO_LaunchByWebServer, wait for the attach to finish before continuing to launch other targets
    **********************************************  defined in vsshell80.idl*/
    /*
    DBGLAUNCH_MergeEnv              = 0x00000080, // provided environment should be merged with system environment
    DBGLAUNCH_DesignTimeExprEval    = 0x00000100, // launched for design-time expression evaluation
    DBGLAUNCH_StopAtEntryPoint      = 0x00000200, // Stop at the entrypoint (step-into)
    DBGLAUNCH_CannotDebugAlone      = 0x00000400, // this process cannot be debugged alone -- stop debugging when only processes with this flag remain
    **********************************************/
    /********************************************** defined in vsshell90.idl
    DBGLAUNCH_WaitForEvent          = 0x00000800  // Debugger should wait for a named event to become signaled after launching the first debug target and before launching more targets
    **********************************************/
    /********************************************** defined in vsshell90.idl (SP1)
    DBGLAUNCH_UseDefaultBrowser     = 0x00001000  // Debugger should use the Default Web Browser; this flag used in conjunction with DLO_LaunchBrowser.
    // The default browser is obtained via IVsUIShellOpenDocument:: GetFirstDefaultPreviewer().
    // The bstrEXE in VsDebugTargetInfo2 points to the URL to be launched. Web Site projects will use
    // this for Silverlight projects. This allows, for example, Firefox to be used which is single
    // instance and so has to be handled differently on launch. Other project systems (e.g. C++) that
    // currently use DLO_LaunchBrowser will continue to use that and IE will get launched as before.
    **********************************************/
    /********************************************* defined in vsshell100.idl (dev10)
    DBGLAUNCH_PrepForDebug          = 0x00002000, // We will eventually debug this process, so allow the debugger to perform additional setup
    DBGLAUNCH_TerminateOnStop       = 0x00004000, // Terminate the debuggee when debugging is stopped. It is an error to specify both this and DBGLAUNCH_DetachOnStop
    DBGLAUNCH_BreakOneProcess       = 0x00008000  // Disable 'Break all processes when one process breaks' debugger option for the debugging session; this option is ignoring if debugging has already started.

    DBGLAUNCH_BlockCredentialsDialog= 0x00010000, // Blocks the creditials dialog from being shown on authentication errors
    DBGLAUNCH_BlockWWSDialog        = 0x00020000, // Blocks the WWS install dialog from being shown
    DBGLAUNCH_StartInSimulator      = 0x00040000  // For DLO_AppPackageDebug, debugger should launch the application (or expect the application to start) in the simulator
    ********************************************** defined in vsshell110.idl (dev11)
    **********************************************/
    /********************************************* defined in vsshell120.idl (dev12)
    DBGLAUNCH_ALLOW_EVENTS_AFTER_STOPPED    = 0x00080000,  // Allows stopping events in break-mode
    DBGLAUNCH_FORCE_32BIT_DEBUG             = 0x00100000,  // Force use of the 32-bit debugger (currently used only for DLO_CreateProcess)
    DBGLAUNCH_FORCE_64BIT_DEBUG             = 0x00200000   // Force use of the 64-bit debugger (currently used only for DLO_CreateProcess)
    ********************************************** defined in vsshell130.idl (dev13)
    **********************************************/
    /********************************************** defined in vsshell140.idl (dev14)
    DBGLAUNCH_ContainsStartupTask           = 0x00400000,  // Use Startup Task activator (currently used only for DLO_AppPackageDebug)
    DBGLAUNCH_Profiling                     = 0x00800000   // Launch process for profiling
    **********************************************/
    /********************************************** defined in vsshell142.idl (dev14)
    DBGLAUNCH_NoTerminateOnImmediateLaunch = 0x01000000   // For DLO_AppPackageDebug, allow app to be running immediately after App Activation.
    **********************************************/
    /********************************************** defined in vsshell154.idl (dev154)
    DBGLAUNCH_ParallelLaunch = 0x02000000
    **********************************************/
    /********************************************** defined in vsshell1548idl (dev158)
    DBGLAUNCH_ForcePseudoRemoteDebug = 0x04000000, // Force usage of a separate debugger worker process (msvsmon.exe) for local debugging
    DBGLAUNCH_IntegratedConsole = 0x08000000 // Application should be launched using the VS integrated console
    **********************************************/
    /********************************************** defined in vsshell160.idl (dev16)
    DBGLAUNCH_BypassAttachSecurity = 0x10000000
    **********************************************/
    DBGLAUNCH_UseIntegratedTerminalService = 0x20000000
};
typedef DWORD VSDBGLAUNCHFLAGS175;


//----------------------------------------------------------------------------
// IVsProjectAsyncOpen
//----------------------------------------------------------------------------
[
    uuid(101d210d-5b28-4e02-b220-19949ff4023b),
    version(1.0),
    pointer_default(unique)
]
interface IVsProjectAsyncOpen : IUnknown
{
    HRESULT OpenItemAsync(
        [in] VSITEMID           itemid,
        [in] GUID               rguidLogicalView,
        [in] VARIANT_BOOL       fShouldGetDocDataFromRdt,
        [in] IUnknown*          punkDocData,
        [out, retval] IVsTask** ppTask);

    HRESULT ReopenItemAsync(
        [in] VSITEMID           itemId,
        [in] GUID               rguidEditorType,
        [in] LPCWSTR            pszPhysicalView,
        [in] GUID               rguidLogicalView,
        [in] VARIANT_BOOL       fShouldGetDocDataFromRdt,
        [in] IUnknown*          punkDocData,
        [out, retval] IVsTask** ppTask);

    HRESULT OpenItemWithSpecificAsync(
        [in] VSITEMID              itemId,
        [in] VSSPECIFICEDITORFLAGS fEditorFlags,
        [in] GUID                  rguidEditorType,
        [in] LPCWSTR               pszPhysicalView,
        [in] GUID                  rguidLogicalView,
        [in] VARIANT_BOOL          fShouldGetDocDataFromRdt,
        [in] IUnknown*             punkDocData,
        [out, retval] IVsTask**    ppTask);
}

[v1_enum] enum __FONTCOLORFLAGS2
{
    FCF_ONLYFIXEDPITCHFONTS = 0x20
};

typedef DWORD FONTCOLORFLAGS2;

[v1_enum] enum __VSSPROPID14
{
    VSSPROPID_ShutdownReason = -9090,
    VSSPROPID_FIRST14        = -9090
};

typedef DWORD VSSPROPID14;

[v1_enum] enum __VSSHUTDOWNREASON
{
    VSSHUTDOWNREASON_SHUTDOWNREASON_ReasonNormalUserInitiated           = 0x0,
    VSSHUTDOWNREASON_SHUTDOWNREASON_ReasonCrash                         = 0x2,
    VSSHUTDOWNREASON_SHUTDOWNREASON_ReasonHang                          = 0x3,
    VSSHUTDOWNREASON_SHUTDOWNREASON_ReasonUnknown                       = 0x4,
    VSSHUTDOWNREASON_SHUTDOWNREASON_NormalNonUserInitiated              = 0x5,
    VSSHUTDOWNREASON_SHUTDOWNREASON_AppRestart                          = 0x6,
    VSSHUTDOWNREASON_SHUTDOWNREASON_Automation                          = 0x7,
    VSSHUTDOWNREASON_SHUTDOWNREASON_OSRequest                           = 0x8,
    VSSHUTDOWNREASON_SHUTDOWNREASON_LicenseValidationFailed             = 0x9,
    VSSHUTDOWNREASON_SHUTDOWNREASON_DefaultIdentityConfigurationBlocked = 0xA
};

typedef DWORD VSSHUTDOWNREASON;

