//=----------------------------------------------------------------------------
// Microsoft Visual Studio
//
// Microsoft Confidential
// Copyright (c) Microsoft Corporation.  All Rights Reserved.
//
// File:     VSShell177.idl
// Contents: the shell interfaces for the entire Dev17 cycle.
//
//
// Current Owner:
//=----------------------------------------------------------------------------
////////////////////////////////////////////////////////////////////////////////

#include "vsshelluuids.h" // for uuid_VsPreserveSigAttribute

#ifndef INTEROPLIB

// Imports - all imports should go here (inside the ifndef)

import "oaidl.idl";
import "ocidl.idl";
import "context.idl";
import "vsshell.idl";
import "vsshell2.idl";
import "vsshell80.idl";
import "vsshell90.idl";
import "vsshell100.idl";
import "vsshell110.idl";
import "vsshell120.idl";
import "vsshell140.idl";
import "vsshell150.idl";
import "vsshell153.idl";
import "vsshell155.idl";
import "vsshell156.idl";
import "vsshell157.idl";
import "vsshell158.idl";
import "vsshell160.idl";
import "vsshell161.idl";
import "vsshell162.idl";
import "vsshell169.idl";
import "vsshell1610.idl";
import "VsPlatformUI.idl";

import "servprov.idl";
import "textfind100.idl";

// Excluding DTE related includes for C builds as they contain C++ only constructs
// and they produce compile errors while building the proxy DLL (msenvXXXp).
cpp_quote("#ifdef __cplusplus")
cpp_quote("#include \"dte.h\"")
cpp_quote("#include \"textmgr2.h\"")
cpp_quote("#include \"guiddef.h\"")
cpp_quote("#endif // __cplusplus")

#endif

//----------------------------------------------------------------------------
// IVsAsyncShellOpenDocument
//----------------------------------------------------------------------------
[
    uuid(6a55d18f-6db5-4993-b503-11eb77949cab),
    version(1.0),
    pointer_default(unique)
]
interface IVsAsyncShellOpenDocument : IUnknown
{
    HRESULT OpenSpecificEditorAsync(
        [in] VSOSPEFLAGS        grfOpenSpecificEditorFlags,
        [in] LPCWSTR            pszDocumentMoniker,
        [in] GUID               guidEditorType,
        [in] LPCWSTR            pszPhysicalView,
        [in] GUID               guidLogicalView,
        [in] LPCWSTR            pszOwnerCaption,
        [in] IVsUIHierarchy*    pHierarchy,
        [in] VSITEMID           vsidItemId,
        [in] VARIANT_BOOL       fShouldGetDocDataFromRdt,
        [in] IUnknown*          punkDocData,
        [in] IServiceProvider*  pServiceProvider,
        [out, retval] IVsTask** ppTask);

    HRESULT OpenStandardEditorAsync(
        [in] VSOSPEFLAGS        grfOpenStandardEditorFlags,
        [in] LPCWSTR            pszDocumentMoniker,
        [in] GUID               guidLogicalView,
        [in] LPCWSTR            pszOwnerCaption,
        [in] IVsUIHierarchy*    pHierarchy,
        [in] VSITEMID           vsidItemId,
        [in] VARIANT_BOOL       fShouldGetDocDataFromRdt,
        [in] IUnknown*          punkDocData,
        [in] IServiceProvider*  pServiceProvider,
        [out, retval] IVsTask** ppTask);

    HRESULT OpenDocumentViaProjectAsync(
        [in]          LPCWSTR      pszDocumentMoniker,
        [in]          GUID         guidLogicalView,
        [in]          VARIANT_BOOL fSupportExternalItems,
        [out, retval] IVsTask**    ppTask);

    HRESULT OpenDocumentViaProjectWithSpecificAsync(
        [in]          LPCWSTR               pszDocumentMoniker,
        [in]          VSSPECIFICEDITORFLAGS grfSpecificEditorFlags,
        [in]          GUID                  guidEditorType,
        [in]          LPCWSTR               pszPhysicalView,
        [in]          GUID                  guidLogicalView,
        [out, retval] IVsTask**             ppTask);

    HRESULT OpenCopyOfStandardEditorAsync(
        [in]          IVsWindowFrame* pOriginalWindowFrame,
        [in]          GUID            guidLogicalView,
        [out, retval] IVsTask**       ppTask);

    HRESULT GetProvisionalViewingStatusForFileAsync(
        [in]          LPCWSTR       pszFileName,
        [in]          IVsHierarchy* pHierarchy,
        [in]          VSITEMID      vsidItemId,
        [in]          GUID          guidLogicalView,
        [out, retval] IVsTask**     ppTask);

    HRESULT GetProvisionalViewingStatusForEditorAsync(
        [in]          GUID      guidEditorType,
        [in]          GUID      guidLogicalView,
        [out, retval] IVsTask** ppTask);
}

//----------------------------------------------------------------------------
// IVsAsyncOpenDocumentResult
//----------------------------------------------------------------------------
[
    uuid(ba346102-ca20-4f19-9d94-a5dab112a262),
    version(1.0),
    pointer_default(unique)
]
interface IVsAsyncOpenDocumentResult : IUnknown
{
    [propget] HRESULT Hierarchy([out, retval] IVsUIHierarchy** ppHierarchy);

    [propget] HRESULT ItemId([out, retval] VSITEMID* pvsidItemId);

    [propget] HRESULT WindowFrame([out, retval] IVsWindowFrame** ppWindowFrame);

    [propget] HRESULT DocumentLoadTask([out, retval] IVsTask** ppTask);
}

//----------------------------------------------------------------------------
// IVsAsyncDeferredDocView
//----------------------------------------------------------------------------
[
    uuid(f3965302-6220-4119-a294-5f0a87e5a4ce),
    version(1.0),
    pointer_default(unique)
]
interface IVsAsyncDeferredDocView : IUnknown
{
    HRESULT LoadDocViewAsync([in] IUnknown* punkDocData, [out, retval] IVsTask** ppTask);
}

//----------------------------------------------------------------------------
// IVsAsyncDocViewResult
//----------------------------------------------------------------------------
[
    uuid(054d0302-f120-4719-8494-5be1a2e04d6a),
    version(1.0),
    pointer_default(unique)
]
interface IVsAsyncDocViewResult : IUnknown
{
    [propget] HRESULT LoadedDocView([out, retval] IUnknown** ppunkLoadedDocView);

    [propget] HRESULT CmdUIGuid([out, retval] GUID* pguidCmdUIGuid);
}

//----------------------------------------------------------------------------
// IVsSettingsStore3
//----------------------------------------------------------------------------
[
    uuid(9572a8d5-0416-4886-b437-ef952590ec3c),
    version(1.0),
    pointer_default(unique)
]
interface IVsSettingsStore3 : IUnknown
{
    HRESULT GetStrings([in] LPCWSTR collectionPath, [in] LPCWSTR propertyName, [out, retval] SAFEARRAY(BSTR) *res);
}

[v1_enum] enum __VsSettingsType2
{
    VsSettingsType2_SettingsType_MultiString = 0x5
};

//----------------------------------------------------------------------
// StatusBarAnimationIndex
//----------------------------------------------------------------------
cpp_quote("#define SBAI3_MIN        8")
cpp_quote("#define SBAI3_HotReload  8")
cpp_quote("#define SBAI3_MAX        8")