//=----------------------------------------------------------------------------
// Microsoft Visual Studio
//
// Microsoft Confidential
// Copyright (c) Microsoft Corporation.  All Rights Reserved.
//
// File:     VSShell1713.idl
// Contents: the shell interfaces for the entire Dev17 cycle.
//
//
// Current Owner:
//=----------------------------------------------------------------------------
////////////////////////////////////////////////////////////////////////////////

#include "vsshelluuids.h" // for uuid_VsPreserveSigAttribute

#ifndef INTEROPLIB

// Imports - all imports should go here (inside the ifndef)

import "oaidl.idl";
import "ocidl.idl";
import "context.idl";
import "vsshell.idl";
import "vsshell2.idl";
import "vsshell80.idl";
import "vsshell90.idl";
import "vsshell100.idl";
import "vsshell110.idl";
import "vsshell120.idl";
import "vsshell140.idl";
import "vsshell150.idl";
import "vsshell153.idl";
import "vsshell155.idl";
import "vsshell156.idl";
import "vsshell157.idl";
import "vsshell158.idl";
import "vsshell160.idl";
import "vsshell161.idl";
import "vsshell162.idl";
import "vsshell169.idl";
import "vsshell1610.idl";
import "VsPlatformUI.idl";

// Excluding DTE related includes for C builds as they contain C++ only constructs
// and they produce compile errors while building the proxy DLL (msenvXXXp).
cpp_quote("#ifdef __cplusplus")
cpp_quote("#include \"dte.h\"")
cpp_quote("#include \"textmgr2.h\"")
cpp_quote("#include \"guiddef.h\"")
cpp_quote("#endif // __cplusplus")

#endif

#ifndef PROXYSTUB_BUILD

//----------------------------------------------------------------------------
// IVsSolutionBuildManager7
//----------------------------------------------------------------------------
[
    uuid(9da1a6a1-7754-43d2-ae47-2e0b5a180e9d),
    version(1.0),
    pointer_default(unique)
]
interface IVsSolutionBuildManager7 : IUnknown
{
    [propget] HRESULT BuildId([out, retval] INT *res);
}

#endif // END PROXYSTUB_BUILD

[v1_enum] enum __ExtendedMessageBoxResult
{
    ExtendedMessageBoxResult_None = 0x0,
    ExtendedMessageBoxResult_OK = 0x1,
    ExtendedMessageBoxResult_Cancel = 0x2,
    ExtendedMessageBoxResult_Abort = 0x3,
    ExtendedMessageBoxResult_Retry = 0x4,
    ExtendedMessageBoxResult_Ignore = 0x5,
    ExtendedMessageBoxResult_Yes = 0x6,
    ExtendedMessageBoxResult_No = 0x7
};

typedef DWORD ExtendedMessageBoxResult;

//----------------------------------------------------------------------------
// IVsUIShell8
//----------------------------------------------------------------------------
[
    uuid(afd581b8-5936-4554-830c-b1bb1ffe2693),
    version(1.0),
    pointer_default(unique)
]
interface IVsUIShell8 : IUnknown
{
    HRESULT ShowMessageBoxEx(
        [in, unique] LPOLESTR title,
        [in] LPOLESTR text,
        [in, unique] LPOLESTR helpTopic,
        [in] OLEMSGBUTTON buttons,
        [in] OLEMSGDEFBUTTON defaultButton,
        [in] OLEMSGICON icon,
        [in] VARIANT_BOOL allowSuppression,
        [out] VARIANT_BOOL* suppressed,
        [out, retval] ExtendedMessageBoxResult* result);

    HRESULT ShowMessageBoxExWithHelpId(
        [in, unique] LPOLESTR title,
        [in] LPOLESTR text,
        [in, unique] LPOLESTR helpFile,
        [in] DWORD helpId,
        [in] OLEMSGBUTTON buttons,
        [in] OLEMSGDEFBUTTON defaultButton,
        [in] OLEMSGICON icon,
        [in] VARIANT_BOOL allowSuppression,
        [out] VARIANT_BOOL* suppressed,
        [out, retval] ExtendedMessageBoxResult* result);
}
