//=----------------------------------------------------------------------------
// Microsoft Visual Studio
//
// Microsoft Confidential
// Copyright (c) Microsoft Corporation.  All Rights Reserved.
//
// File:     VSShell174.idl
//
//
// Current Owner:
//=----------------------------------------------------------------------------
////////////////////////////////////////////////////////////////////////////////

#include "vsshelluuids.h" // for uuid_VsPreserveSigAttribute

#ifndef INTEROPLIB

// Imports - all imports should go here (inside the ifndef)

import "oaidl.idl";
import "ocidl.idl";
import "context.idl";
import "vsshell.idl";
import "vsshell2.idl";
import "vsshell80.idl";
import "vsshell90.idl";
import "vsshell100.idl";
import "vsshell110.idl";
import "vsshell120.idl";
import "vsshell140.idl";
import "vsshell150.idl";
import "vsshell153.idl";
import "vsshell155.idl";
import "vsshell156.idl";
import "vsshell157.idl";
import "vsshell158.idl";
import "vsshell160.idl";
import "vsshell161.idl";
import "vsshell162.idl";
import "vsshell169.idl";
import "vsshell1610.idl";
import "VsPlatformUI.idl";


// Excluding DTE related includes for C builds as they contain C++ only constructs
// and they produce compile errors while building the proxy DLL (msenvXXXp).
cpp_quote("#ifdef __cplusplus")
cpp_quote("#include \"dte.h\"")
cpp_quote("#include \"textmgr2.h\"")
cpp_quote("#include \"guiddef.h\"")
cpp_quote("#endif // __cplusplus")

#endif

[v1_enum] enum __VSSPROPID13
{
    VSSPROPID_EnableEnhancedTooltips = -9088,
    VSHPROPID_SlowEnumeration        = -9089,

    // !!!! NOTE !!!!   THIS MUST BE THE SAME AS THE LAST PROP DEFINED
    // when this is extended in the next version idl, uses of it must be changed to the new value
    VSSPROPID_FIRST13                = -9089
};

typedef DWORD VSSPROPID13;

#ifndef PROXYSTUB_BUILD

//----------------------------------------------------------------------------
// IVsAsyncCommandParameters
//----------------------------------------------------------------------------
[
    uuid(1553ee45-0c52-4aa4-ab21-f1769749bc7a),
    version(1.0),
    pointer_default(unique)
]
interface IVsAsyncCommandParameters : IUnknown
{
    [propget] HRESULT ShouldRunAsync([out, retval] BOOL* res);

    [propget] HRESULT OriginalArgument([out, retval] VARIANT* res);
}

#endif

[v1_enum] enum __FCSTORAGEFLAGS2
{
    FCSF_AVOIDPACKAGELOAD = 0x00000010
};

