# Generated by Django 5.1.2 on 2025-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts_Config',
            fields=[
                ('account_id', models.IntegerField(primary_key=1, serialize=False, verbose_name='账号Id')),
                ('account_name', models.CharField(max_length=50, verbose_name='用户名')),
                ('my_password', models.CharField(max_length=50, verbose_name='密码')),
                ('account_mail', models.EmailField(max_length=254)),
                ('account_authority', models.CharField(blank=True, choices=[('A', 'PL'), ('B', 'TL'), ('C', 'DBA'), ('D', 'TA')], max_length=50, verbose_name='权限代码')),
                ('account_create_time', models.DateTimeField(blank=True, verbose_name='账号创建时间')),
                ('account_update_time', models.DateTimeField(blank=True, verbose_name='账号更新时间')),
                ('account_validity', models.IntegerField(blank=True, max_length=10, verbose_name='账号有效期')),
                ('authority_code', models.CharField(blank=True, max_length=50, verbose_name='权限代码')),
            ],
            options={
                'verbose_name': '账号&权限',
                'verbose_name_plural': '账号配置',
            },
        ),
        migrations.CreateModel(
            name='Databases_Config',
            fields=[
                ('DB_id', models.IntegerField(primary_key=1, serialize=False, verbose_name='主键ID')),
                ('DB_type', models.CharField(max_length=30, verbose_name='数据库类型')),
                ('DB_name', models.CharField(max_length=50, verbose_name='数据库实例名称')),
                ('DB_user', models.CharField(blank=True, max_length=30, verbose_name='数据库连接账号')),
                ('DB_password', models.CharField(blank=True, max_length=50, verbose_name='密码')),
                ('DB_port', models.IntegerField(blank=True, max_length=10, verbose_name='端口号')),
                ('DB_platform', models.CharField(blank=True, max_length=30, verbose_name='平台类型')),
                ('last_updatetime', models.DateTimeField(blank=True, verbose_name='上次更新时间')),
                ('DB_endpoint', models.CharField(blank=True, max_length=50, verbose_name='数据库地址/终端节点')),
                ('DB_access_cmd', models.CharField(blank=True, max_length=50, verbose_name='数据库快捷登录命令')),
            ],
            options={
                'verbose_name': '数据库配置',
                'verbose_name_plural': '数据库配置',
            },
        ),
        migrations.CreateModel(
            name='Monitoring_Config',
            fields=[
                ('metric_id', models.IntegerField(primary_key=1, serialize=False, verbose_name='指标Id')),
                ('metric_name', models.CharField(max_length=30, verbose_name='监控指标名')),
                ('metric_db_type', models.CharField(blank=True, max_length=30, verbose_name='数据库类型')),
                ('metric_access', models.CharField(blank=True, max_length=50, verbose_name='指标获取方式')),
                ('metric_instance', models.CharField(blank=True, max_length=50, verbose_name='监控目标')),
                ('metric_threshold', models.IntegerField(blank=True, max_length=10, verbose_name='告警阈值')),
                ('metric_frequency', models.CharField(blank=True, max_length=30, verbose_name='触发频率')),
                ('metric_notification', models.CharField(blank=True, max_length=30, verbose_name='告警方式')),
            ],
            options={
                'verbose_name': '监控指标配置',
                'verbose_name_plural': 'Metric',
            },
        ),
    ]
