# Generated by Django 5.1.2 on 2025-06-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts_Config',
            new_name='Accounts_Configurations',
        ),
        migrations.RenameModel(
            old_name='Databases_Config',
            new_name='Databases_Configurations',
        ),
        migrations.RenameModel(
            old_name='Monitoring_Config',
            new_name='Monitoring_Configurations',
        ),
        migrations.AlterModelOptions(
            name='monitoring_configurations',
            options={'verbose_name': '监控指标配置', 'verbose_name_plural': '监控项配置'},
        ),
    ]
