# Generated by Django 5.1.2 on 2025-06-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0002_rename_accounts_config_accounts_configurations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases_configurations',
            name='DB_type',
            field=models.CharField(choices=[('Oracle', 'Oracle'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('Redis', 'Redis'), ('Cassandra', 'Cassandra'), ('MongoDB', 'MongoDB')], max_length=30, verbose_name='数据库类型'),
        ),
    ]
