# Generated by Django 5.1.2 on 2025-06-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0003_alter_databases_configurations_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring_configurations',
            name='metric_db_type',
            field=models.CharField(choices=[('Oracle', 'Oracle'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('Redis', 'Redis'), ('Cassandra', 'Cassandra'), ('MongoDB', 'MongoDB')], max_length=30, verbose_name='数据库类型'),
        ),
    ]
