# Generated by Django 5.1.2 on 2025-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup_Restore',
            fields=[
                ('backup_id', models.IntegerField(primary_key=1, serialize=False, verbose_name='备份任务ID')),
                ('backup_db_type', models.CharField(choices=[('A', 'Oracle'), ('B', 'MySQL'), ('C', 'Redis'), ('D', 'PostgreSQL'), ('E', 'MangoDB'), ('F', 'Cassandra')], max_length=30, verbose_name='数据库类型')),
                ('backup_db_version', models.CharField(max_length=30, verbose_name='数据库版本')),
                ('backup_instance', models.CharField(max_length=30, verbose_name='实例名')),
                ('backup_db_name', models.CharField(max_length=30, verbose_name='数据库名')),
                ('backup_tb_name', models.CharField(max_length=30, verbose_name='表名')),
                ('backup_type', models.CharField(max_length=30, verbose_name='备份类型')),
                ('backup_way', models.CharField(max_length=30, verbose_name='备份方式')),
                ('backup_frequency', models.CharField(max_length=30, verbose_name='备份频率')),
                ('backup_create_time', models.DateTimeField(blank=True, verbose_name='备份创建时间')),
                ('backup_path', models.URLField(blank=True, verbose_name='备份路径')),
            ],
            options={
                'verbose_name': '备份&恢复',
                'verbose_name_plural': 'BackUp_Restore',
            },
        ),
        migrations.CreateModel(
            name='Maintenances_Operation',
            fields=[
                ('m_id', models.IntegerField(primary_key=1, serialize=False, verbose_name='事件记录ID')),
                ('m_db_type', models.CharField(max_length=30, verbose_name='事件数据库类型')),
                ('m_instance', models.CharField(max_length=30, verbose_name='事件类型')),
                ('m_operation_type', models.CharField(max_length=30, verbose_name='事件操作类型')),
                ('m_operation_time', models.DateTimeField(blank=True, verbose_name='事件起止时间')),
                ('m_alter_status', models.CharField(choices=[('A', 'Mute'), ('B', 'Unmute')], max_length=30, verbose_name='监控告警状态')),
                ('m_operation', models.CharField(max_length=30, verbose_name='操作')),
            ],
            options={
                'verbose_name': '维护事件处理',
                'verbose_name_plural': 'Maintenances_Operation',
            },
        ),
    ]
