# Generated by Django 5.1.2 on 2025-06-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Backup_Restore',
            new_name='Backup_Restore_Operation',
        ),
        migrations.RenameModel(
            old_name='Maintenances_Operation',
            new_name='Maintenances_Operations',
        ),
    ]
