# Generated by Django 5.1.2 on 2025-06-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0002_rename_backup_restore_backup_restore_operation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup_restore_operation',
            options={'verbose_name': '备份&恢复', 'verbose_name_plural': '备份&恢复-BackUp_Restore'},
        ),
        migrations.AlterModelOptions(
            name='maintenances_operations',
            options={'verbose_name': '维护事件处理', 'verbose_name_plural': '维护事件处理-Maintenances_Operation'},
        ),
    ]
